### ISSUE TITLE
How to Download video 

### ISSUE THREAD

**Issue by kmadhusmk** [omansak/libvideo#1]
I could not find any method for downloading physical video file into client machine folder. Can you please suggest how can i download a video using this api

**Comment by jkw117** [comment]
James-Ko,

Is there a way to support downloading restricted content. I’ve seen several blogs which use youtube to secure their video's by content rating as well as restricting specified user accounts to access them (paid content). How easy do you think that would be to enable downloading of this content? I have an app that downloads videos/images from Tumblr and youtube is a major one. And I’ve seen a few apps on the stores that say they do this, I’m just trying to see how to enable this content. 

I currently use youtubextractor, but plan on testing out your libvideo, and probably switching to it.

**Comment by jamesqo** [comment]
@swethamadhu Sure, it's easy. Have you checked [the docs](https://github.com/James-Ko/libvideo/tree/master/docs)?

Here's a two-liner to download a video and drop it into a file:

``` csharp
var video = new YouTubeService().GetVideo("[video link goes here]");
File.WriteAllBytes(video.GetBytes(), Path.Combine("[folder you need to save it to]", video.Title + video.Extension));
```

---

@jkw117 Probably not. libvideo scans the page source for any encoded links, and downloads the videos from them. With restricted content, it's likely that YouTube simply won't include the links at all.

It might be possible if we introduced some kind of authorization scheme and fiddled around with the HTTP request headers a little bit, though. You can open a new issue and we'll talk about it there.
