### ISSUE TITLE
Additional information: GetDecryptionFunction failed

### ISSUE THREAD

**Issue by megy2012** [omansak/libvideo#107]
Codes:

        If FolderBrowserDialog1.ShowDialog = DialogResult.OK Then

            Dim video = YouTube.Default.GetVideo(TextBox1.Text)
            MessageBox.Show(video.IsEncrypted.ToString)
            File.WriteAllBytes(FolderBrowserDialog1.SelectedPath + "\" + video.FullName, video.GetBytes())

        End If

I  am using 1.4.0 version of libvideo and I found out that when "video.IsEncrypted.ToString = False" it downloads video with no problems but when it's "True" it shows error. Can you help me ?

**Comment by omansak** [comment]
Please use https://github.com/omansak/libvideo

**Comment by megy2012** [comment]
I tried install it more times but it writes that.
![aaa](https://user-images.githubusercontent.com/43544216/45973527-08eca800-c03f-11e8-92ea-50112b3bbb62.png)

...and i was using that (https://www.nuget.org/packages/VideoLibrary) but 1.4.0, bucause newer versions show that error.

**Comment by i3arnon** [comment]
[Version 2.0.2](https://www.nuget.org/packages/VideoLibrary/2.0.2) that I recently published should fix it.
Please reopen the issue if it doesn't.
Sorry for taking so long to get to it.
