### ISSUE TITLE
720p new videos no longer has no sound

### ISSUE THREAD

**Issue by omansak** [omansak/libvideo#108]
Video format is 36 has no sound 720p

**Comment by omansak** [comment]
@hig-dev do you know any solution on UWP?

**Comment by i3arnon** [comment]
@omansak Do you have an example of where that happens?

**Comment by szblajos** [comment]
@i3arnon , @omansak is right. Looks like YouTube somehow replaced audio tracks for all 720p videos.
You can't download 720p vids with libvideo anymore. It gets only the 360p links to download instead.
Please, determine the AudioType with libvideo.compat library for 720p videos. They're all in the format: YoutubeExtractor.AudioType.Unknown
Here's a link for example: https://www.youtube.com/watch?v=8CdcCD5V-d8

**Comment by i3arnon** [comment]
@szblajos correct me if I'm wrong, but it's not that you can't download 720p videos at all, you just can't download 720p with sound (i.e. where `IsAdaptive == false`), right?

**Comment by omansak** [comment]
@i3arnon @szblajos it's right

**Comment by i3arnon** [comment]
AFAICS there's not much to do about it.
Although this video (`8CdcCD5V-d8`) has unknown streams from a new video format: AV1 (#112), all 720p streams are "adaptive" and the video and audio are separate.

The only way to get a 720p with sound is to download the video and audio separately and merge them together.

**Comment by omansak** [comment]
@i3arnon do you know any merge library ?

**Comment by i3arnon** [comment]
@omansak ffmpeg

**Comment by PhilBu96** [comment]
@i3arnon I don't really know how to download ONLY the video... When I try to download for example an adaptive video, when I start the download, nothing happens and my program freezes...

**Comment by omansak** [comment]
Fixed. Update 3.0.0
