### ISSUE TITLE
Video download doesn't work for every Video (v.2.0.1)

### ISSUE THREAD

**Issue by MusMuss1** [omansak/libvideo#109]
Hey, idk if this problem is already known, but video download like this (https://www.youtube.com/watch?v=5-xhpcgBMe4&start_radio=1&list=RDMM5-xhpcgBMe4)
doesn't work at the moment. 
encryption link calls "Access denied"

Thank You :)

**Comment by i3arnon** [comment]
[Version 2.0.2](https://www.nuget.org/packages/VideoLibrary/2.0.2) that I recently published should fix it.
Please reopen the issue if it doesn't.
Sorry for taking so long to get to it.

**Comment by MusMuss1** [comment]
Hey, thank You very very much. It works again, but there is one little problem, the maximum Videoquality is 360p and audio only 96 kbit/s. Maybe you can tell why it is or fix it.

Thanks a lot :)

**Comment by i3arnon** [comment]
@MusMuss1 see #108
