### ISSUE TITLE
GetVideo is not working.

### ISSUE THREAD

**Issue by Maik8** [omansak/libvideo#110]
I just try to download a video like this:

`YouTube youtube = YouTube.Default;                                       
var vid = youtube.GetVideo(tbLink.Text);`

This gives me the following Error:

System.Net.Http.HttpRequestException: Der Antwortstatuscode gibt keinen Erfolg an: 403 (Forbidden).
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei VideoLibrary.VideoClient.<GetBytesAsync>d__10.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei VideoLibrary.Video.<GetBytesAsync>d__11.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei VideoLibrary.Video.GetBytes()

I am using Visual Studio 2015 Enterprise and libvideo 2.0.1 
I add the sample project i used as a .zip here.
[Sample.zip](https://github.com/i3arnon/libvideo/files/2429200/Sample.zip)

**Comment by omansak** [comment]
use https://github.com/omansak/libvideo

**Comment by Maik8** [comment]
Thanks for the answer but it is still not working, this time it crashes with ths error message:
GER: `Ein Ausnahmefehler des Typs "System.AggregateException" ist in mscorlib.dll aufgetreten.`
ENG: `An exeption of type "System.AggregateException" occupied in mscorlib.dll.`

Hope that helps, maybe you know what's wrong / what i do wrong.
Thanks in advance!

**Comment by haiduong87** [comment]
Hello @omansak 
I tried to install from nuget,  it  get 403 error
I tried downgrade to 2.0, it still didn't work.
Then I tried https://github.com/omansak/libvideo (downloaded and attached to my project), and it worked.
But both repos have the same nuget name. I can't understand...

**Comment by omansak** [comment]
my fork is not install nuget. @haiduong87 remove orjinal package from nuget or try @hig-dev nuget package

**Comment by ghost** [comment]
> use https://github.com/omansak/libvideo
Don't work if video has signature.

**Comment by i3arnon** [comment]
[Version 2.0.2](https://www.nuget.org/packages/VideoLibrary/2.0.2) that I recently published should fix these issues.
Please open/reopen an issue with the video URL/ID if it doesn't.
Sorry for taking too long to get to it.
