### ISSUE TITLE
GetBytes() method not working for downloading the video

### ISSUE THREAD

**Issue by jayotirana** [omansak/libvideo#111]
Hi @i3arnon 
I tried to download the video using libvideo latest version i. e 2.0.1 and also tried other older versions, but it's not working and I am getting the error:

System.Exception: GetDecryptionFunction failed
Response status code does not indicate success: 403 (Forbidden).

I am able to get the video details like duration, Name etc, but not the bytes. I am using Visual Studio 2017.

**Comment by i3arnon** [comment]
[Version 2.0.2](https://www.nuget.org/packages/VideoLibrary/2.0.2) that I recently published should fix it.
Please reopen with the video URL/ID if it doesn't.
Sorry for taking too long to get to it.

**Comment by jayotirana** [comment]
Thanks for the update @i3arnon. I am testing with version 2.0.2, I will reopen if found any issue.

**Comment by jayotirana** [comment]
Hello @i3arnon,
I am done with my testing and I am able to download the video from the youtube URL. It's successfully downloaded in the specified path.

Thanks again for resolving this issue.

**Comment by Gart79** [comment]
Hi, I ran into the same issue with version 2.0.3. Some are working but e.g. video-id: Rbm6GXllBiw  not. 
Thanks in advance!!
