### ISSUE TITLE
Issue getting bytes

### ISSUE THREAD

**Issue by adavid1** [omansak/libvideo#114]
(I have the version 2.0.2)

var youtube = YouTube.Default;
var vid = youtube.GetVideo(link);
var video = vid.GetBytes();

The program is raising an error for the vid.GetBytes()
The error is : 
System.Exception: 'GetDecryptionFunction failed'

**Comment by AesirMacGregor** [comment]
I have the same problem. Noteable: 4days ago it worked.

**Comment by omansak** [comment]
Update Regex Function in YouTubeVideo.Decrypt

\bc\s*&&\s*d\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*([a-zA-Z0-9$]+)\(

Credit : https://github.com/Tyrrrz/YoutubeExplode/commit/27a4a421c14705fd98f59db71ec3cd379ab1e046

or

\((\w+)\(\([a-zA-Z0-9$]*,window.decodeURIComponent\)\(\w+\)\)\)

Credit : @omansak 


or you can use my fork with dynamic regex service : 
https://github.com/omansak/libvideo

**Comment by candogusyilmaz** [comment]
> Update Regex Function in YouTubeVideo.Decrypt
> 
> \bc\s*&&\s_d.set([^,]+\s_,\s*([^)]_)\s_(\s*([a-zA-Z0-9$]+)(
> 
> Credit : [Tyrrrz/YoutubeExplode@27a4a42](https://github.com/Tyrrrz/YoutubeExplode/commit/27a4a421c14705fd98f59db71ec3cd379ab1e046)
> 
> or
> 
> ((\w+)(([a-zA-Z0-9$]*,window.decodeURIComponent)(\w+)))
> 
> Credit : @omansak
> 
> or you can use my fork with dynamic regex service :
> https://github.com/omansak/libvideo

I think there is still an issue with Regex Function. I used your fork but it didn't work either. Do you have any new solutions for this problem?

**Comment by omansak** [comment]
@candogusyilmaz sorun tam olarak nedir acaba ? Çünkü ben uzun süredir kullanıyorum bir hata yok.

**Comment by omansak** [comment]
@candogusyilmaz and you need change regex group 1 from 3 https://github.com/i3arnon/libvideo/blob/53af4b2915349012573003576997022ebd374ceb/src/libvideo/YouTubeVideo.Decrypt.cs#L87

**Comment by candogusyilmaz** [comment]
@omansak Teşekkürler

**Comment by i3arnon** [comment]
Should be fixed with [v2.0.3](https://www.nuget.org/packages/VideoLibrary/2.0.3)
Please reopen the issue if that's not the case.

**Comment by bugman123** [comment]
I installed VideoLibrary 2.0.3 yesterday and it worked great, but today I am also getting the "GetDecryptionFunction failed" exception when I call video.GetBytes().

**Comment by Gr3gorywolf** [comment]
@bugman123 @omansak help us pls

**Comment by omansak** [comment]
@Gr3gorywolf  new regex 

`\bc\s*&&\s*d\.set\([^,]+\s*,[^(]*\(([a-zA-Z0-9$]+)\(`

**Comment by omansak** [comment]
@Gr3gorywolf @bugman123  

`c&&d.set(b,encodeURIComponent(fv(decodeURIComponent(c))));return d};`
we must find 'fv' with regex  `\bc\s*&&\s*d\.set\([^,]+\s*,[^(]*\(([a-zA-Z0-9$]+)\( `

You must replace this line https://github.com/i3arnon/libvideo/blob/586421e0f39367d79b437daa517d3c008f0d20eb/src/libvideo/YouTubeVideo.Decrypt.cs#L13 with code in below : 

`private static readonly Regex DecryptionFunctionRegex = new Regex(@"\bc\s*&&\s*d\.set\([^,]+\s*,[^(]*\(([a-zA-Z0-9$]+)\(");`


or you can use my form : https://github.com/omansak/libvideo (#118 )

**Comment by Gr3gorywolf** [comment]
@omansak thank u and actually i use ur fork due the dynamic regex service

**Comment by omansak** [comment]
@Gr3gorywolf you can use own dropbox instead of my account

**Comment by Gr3gorywolf** [comment]
@omansak dropbox didnt have request limits etc right?

**Comment by LaSerDnc** [comment]
@i3arnon 
Hi, I was wondering when this fix is pushed to a new release. I have the same issue and I use the 2.03 from NuGet. BTW thanks for the excellent tool!

**Comment by fortunecafe5** [comment]
Where can i find the .cs files i have downloaded this with Nuget-Manager? How can i edit this? :-(
