### ISSUE TITLE
Get Direct Link  from youtube

### ISSUE THREAD

**Issue by manii-stack** [omansak/libvideo#115]
Hi
I just need to get a direct download link(.mp4) from specific youtube URL.
Is it possible with this library?

**Comment by i3arnon** [comment]
You can get a direct link to the video's stream. You can see one example [here](https://github.com/i3arnon/YouCast/blob/31c09b9b428711167472d546beb21091cf82d9cc/src/Service/YoutubeFeed.cs#L300)
