### ISSUE TITLE
Video URL not correct in NET Core project

### ISSUE THREAD

**Issue by iancona** [omansak/libvideo#116]
I've used and keep using this library for my UWP project and tried also with xamarin and the given URL for watching a video from ID, is correct, and it works also on any browser.
I've tried to implement this library in a NET core with same code, the url given is incorrect and the response is 403 error forbidden.

**Comment by i3arnon** [comment]
Can you give an example for a video that doesn't work for you in .NET Core but works elsewhere?

**Comment by iancona** [comment]
Yes. 
DM_h_rx6WtE 
or
bo_efYhYU2A
