### ISSUE TITLE
GetDecryptionFunction failed

### ISSUE THREAD

**Issue by patachi** [omansak/libvideo#119]
looks like the decryption regex need to be updated

**Comment by Gr3gorywolf** [comment]
#114 omansak fixed this issue

**Comment by ReMinoer** [comment]
Hi,

Actually it seems it's a new issue. I got the error on fork https://github.com/hig-dev/libvideo first. Then I checked with your original repo and got the same. It was working just fine on that fork yesterday.

My exception:
```
Message: GetDecryptionFunction failed

Callstack:
   à VideoLibrary.YouTubeVideo.GetDecryptionFunction(String js)
   à VideoLibrary.YouTubeVideo.GetDecryptionFunctionLines(String js)
   à VideoLibrary.YouTubeVideo.DecryptSignature(String js, String signature)
   à VideoLibrary.YouTubeVideo.<DecryptAsync>d__21.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à VideoLibrary.YouTubeVideo.<GetUriAsync>d__13.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   à YoutubeDotMp3.ViewModels.OperationViewModel.<DownloadAsync>d__61.MoveNext() dans D:\Remi\Git\YoutubeDotMp3\YoutubeDotMp3\ViewModels\OperationViewModel.cs:ligne 278
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   à YoutubeDotMp3.ViewModels.OperationViewModel.<RunAsync>d__57.MoveNext() dans D:\Remi\Git\YoutubeDotMp3\YoutubeDotMp3\ViewModels\OperationViewModel.cs:ligne 154
```

**Comment by omansak** [comment]
@ReMinoer  https://github.com/i3arnon/libvideo/issues/114#issuecomment-455711935 or use #118

**Comment by ReMinoer** [comment]
Sorry I didn't scroll. -_-"
Thank you for the fix. :)

**Comment by andrey-infinity** [comment]
Can you please update the NuGet ?

**Comment by this-is-r-gaurav** [comment]
Do You get the Patch For the Same? @patachi I tried @omansak Package but it's not available on nuget, can You have a look at this issue @i3arnon Please

**Comment by Gr3gorywolf** [comment]
@this-is-r-gaurav hmm you must clone the omansak's libvideo repo and then compile it and add the dll to your proyect. Otherwise there's no way to use the omansak's version

**Comment by omansak** [comment]
@SiTox @this-is-r-gaurav This project has licence so i dont upluoad tı Nuget. You can clone my form

**Comment by this-is-r-gaurav** [comment]
@omansak Okay I was just new to dot net so trying to reduce the building the scratch code, But anyway i will try thank you

**Comment by andrey-infinity** [comment]
Sorry, this is slightly confusing for me. Is there general agreement, which libvideo is the main/freshest and maintainable? and which one is actually published to Nuget ? And what is the reason for having multiple forks? sorry for stupid questions.

**Comment by Gr3gorywolf** [comment]
@SiTox because the owner dont accept some   pending pull request i guess

**Comment by ReMinoer** [comment]
If you want a Nuget, VideoLibraryHIG 1.5.3 ([hig-dev/libvideo](https://github.com/hig-dev/libvideo)) has the fix.

**Comment by this-is-r-gaurav** [comment]
@ReMinoer This ain't working in my case i tried this. It was not able to detect the namespace VideoLibrary

**Comment by this-is-r-gaurav** [comment]
@omansak hey I tried your dynamic url repo I am getting following error now .

Inner Exception 1:
ArgumentException: parsing "\bc\s*&&\s_d.set([^,]+\s_,\s*([^)]_)\s_(\s*([a-zA-Z0-9$]+)(" - Not enough )'s.

**Comment by omansak** [comment]
@this-is-r-gaurav can you give more informations and urls ? are you sure use last version at my fork ?

**Comment by this-is-r-gaurav** [comment]
Yes Master Branch, I just picker random video, But i switched to some other Package Now. Youtube Explode Thanks For the help.

**Comment by GuggeB** [comment]
I'm using the latest version.
For example  https://www.youtube.com/watch?v=e3Fir4sdHm0  works fine
But when I try  https://www.youtube.com/watch?v=LauDl7qwcA0  I get:
System.Exception: GetDecryptionFunction failed
at line 26 in YouTubeVideo.Decrypt.cs
- line 26: GetBytesAsync().GetAwaiter().GetResult();

**Comment by kevieman** [comment]
Hey there, I still have this issue. I have tried #114 and #118 but this doesnt help. It only applie swhen i try to run my UWP app on my laptop. On my desktop it works fine.

**Comment by Alois-xx** [comment]
> 
> 
> If you want a Nuget, VideoLibraryHIG 1.5.3 ([hig-dev/libvideo](https://github.com/hig-dev/libvideo)) has the fix.

The Fork from hig-dev is working on April 2019 compared to the base version. Good work by bringing also code from YoutubeExploder which is much cleaner onboard.

**Comment by RexfelisLOC** [comment]
Not sure why, but when my app goes into background mode the VideoLibraryHIG causes memory to spike.  Commenting out the two lines of code I use from the library returns memory usage to normal.  At any rate it makes background UWP playback nearly impossible because it always pushes it over the 128MB limit.
