### ISSUE TITLE
GetUri Exception

### ISSUE THREAD

**Issue by SergeyDCT** [omansak/libvideo#124]
var video = cli.GetVideo(query);
                    string uri = video.GetUri();

                    try
                    {
                        var uris = DownloadUrlResolver
                            .GetDownloadUrls(query)
                            .Select(v => v.DownloadUrl);

                        Console.WriteLine($"Link #{i + 1}");
                        foreach (var v in uris)
                        {
                            Console.WriteLine(v);
                            Console.WriteLine();
                        }
                    }
                    catch(Exception ex)
                    {
                    }

I get Exception Message
Could not parse the Youtube page for URL http://youtube.com/watch?v=2vjPBrBU-TM\nThis may be due to a change of the Youtube page structure.\nPlease report this bug at www.github.com/flagbug/YoutubeExtractor/issues

**Comment by Gr3gorywolf** [comment]
@omansak what is the new decrypt regex??

**Comment by omansak** [comment]
@Gr3gorywolf It is not decrypt issue. Randomly Youtube generate different signature . I working on it

**Comment by omansak** [comment]
@Gr3gorywolf  @SergeyDCT  test my last commit #125 (https://github.com/omansak/libvideo)

**Comment by SergeyDCT** [comment]
> 
> 
> @Gr3gorywolf @SergeyDCT test my last commit #125 (https://github.com/omansak/libvideo)

thank you!

**Comment by SergeyDCT** [comment]
> 
> 
> @Gr3gorywolf @SergeyDCT test my last commit #125 (https://github.com/omansak/libvideo)

var video = cli.GetVideo("https://www.youtube.com/watch?v=4OH3JZyLVJE");
string uri = video.GetUri();
this.mediaElement.Source = new Uri(uri);
I get an error while playing this uri. MediaElement Failed with Exception ErrorMessage = "MF_MEDIA_ENGINE_ERR_DECODE : HRESULT - 0xC00D4A3E"

**Comment by omansak** [comment]
@SergeyDCT it's decrypt issue.

New Regez : `\bc\s*&&\s*a\.set\([^,]+,\s*(?:encodeURIComponent\s*\()?\s*([\w$]+)\(`

**Comment by omansak** [comment]
@SergeyDCT test my last commit #125 (https://github.com/omansak/libvideo)

**Comment by SergeyDCT** [comment]
> 
> 
> @SergeyDCT it's decrypt issue.
> 
> New Regez : `\bc\s*&&\s*a\.set\([^,]+,\s*(?:encodeURIComponent\s*\()?\s*([\w$]+)\(`

thank you
