### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Qandil** [omansak/libvideo#13]
It would be nice to list the changes on the library landing page, showing the updates been made so far.

**Comment by jamesqo** [comment]
Agreed, I've been making quite a few breaking changes lately (apologies to those who've updated the package). I can't make one right now (busy atm), but I will when I'm free on Sunday. Thanks @Qandil.

**Comment by jamesqo** [comment]
[Added!](https://github.com/jamesqo/libvideo/blob/master/changelog.md)
