### ISSUE TITLE
(403) Frobidden is back. on GetBytes()

### ISSUE THREAD

**Issue by yoirgl** [omansak/libvideo#133]
everything is on the title : getting 403 forbidden on all videos. 
example : http://www.youtube.com/watch?v=tAGnKpE4NCI

**Comment by ColorTwist** [comment]
same error for all videos.
Youtube changed something- again.

**Comment by omansak** [comment]
Trymy last commit (https://github.com/omansak/libvideo)

**Comment by ColorTwist** [comment]
Seems to be fine now.
Thanks!

**Comment by yoirgl** [comment]
> 
> 
> Trymy last commit (https://github.com/omansak/libvideo)

good work !

**Comment by ReazerDev** [comment]
> Trymy last commit (https://github.com/omansak/libvideo)

Hi, I can't compile libvideo. I get 
- Field "YouTubeVideo.DFunctionRegex" is never assigned to, and will always have its default value null (File YouTubeVideo.Decrypt.cs, Line 14)
- The name "DFunctionRegex_Dynamic" does not exist in the current context. (File YouTubeVideo.cs Line 24 and 26)
I'm not good with Regex and therefore can't fix it myself ^^

**Comment by omansak** [comment]
> > Trymy last commit (https://github.com/omansak/libvideo)
> 
> Hi, I can't compile libvideo. I get
> 
> * Field "YouTubeVideo.DFunctionRegex" is never assigned to, and will always have its default value null (File YouTubeVideo.Decrypt.cs, Line 14)
> * The name "DFunctionRegex_Dynamic" does not exist in the current context. (File YouTubeVideo.cs Line 24 and 26)
>   I'm not good with Regex and therefore can't fix it myself ^^

ok i fixed, try again

**Comment by ReazerDev** [comment]
> > > Trymy last commit (https://github.com/omansak/libvideo)
> > 
> > 
> > Hi, I can't compile libvideo. I get
> > 
> > * Field "YouTubeVideo.DFunctionRegex" is never assigned to, and will always have its default value null (File YouTubeVideo.Decrypt.cs, Line 14)
> > * The name "DFunctionRegex_Dynamic" does not exist in the current context. (File YouTubeVideo.cs Line 24 and 26)
> >   I'm not good with Regex and therefore can't fix it myself ^^
> 
> ok i fixed, try again

It works. Thanks!

**Comment by omansak** [comment]
Fixed. Update 3.0.0
