### ISSUE TITLE
Nearly all of the videos are failing

### ISSUE THREAD

**Issue by TheUnstoppable** [omansak/libvideo#138]
As seen on the title, most of the videos are failing to decipher. Is there a change in YouTube or am I doing something wrong? There are some working videos too. Like "https://www.youtube.com/watch?v=0Yy9YzdmTJA" does not work, while "https://www.youtube.com/watch?v=D6qCo5LA0wU" work.

**Comment by omansak** [comment]
Use my stable fork https://github.com/omansak/libvideo

**Comment by omansak** [comment]
Fixed. Update 3.0.0
