### ISSUE TITLE
GetEncryptionFunction Failed version 2.03

### ISSUE THREAD

**Issue by kkfrosty** [omansak/libvideo#139]
`
           var source = filePath;
            var youtube = YouTube.Default;
            var vid = youtube.GetVideo(youTubeUrl);
                       
            File.WriteAllBytes(source + vid.FullName, vid.GetBytes()); < -- Fails here

            var inputFile = new MediaFile { Filename = source + vid.FullName };
            var outputFile = new MediaFile { Filename = $"{mp3Name}.mp3" };

            using (var engine = new Engine())
            {
                engine.GetMetadata(inputFile);

                engine.Convert(inputFile, outputFile);
            }
`

**Comment by Gr3gorywolf** [comment]
@omansak  do u know the new decrypt regex??

**Comment by omansak** [comment]
My fork has no issue.

**Comment by Headhuntez** [comment]
> My fork has no issue.

how to set your fork? I installed the package with gunet. as I understand it is the original. and how to replace it with your fork, please help, I'm a complete beginner.

(I got the same error)

**Comment by TheUnstoppable** [comment]
YouTube probably changed their encrpytion system, or something related to it. Because most of the newest musics, or contents fails. (Issue #138 )

**Comment by kkfrosty** [comment]
There is an issue, I use HD Video Converter Factory and it works with the same links.

**Comment by omansak** [comment]
@Gr3gorywolf i pushed update at my fork maybe can you test ?

**Comment by Gr3gorywolf** [comment]
@omansak what u changed un the last commit?

**Comment by omansak** [comment]
Some videos has problem such as 
Normal : Alr26K0F4EQ
Encrypted : ADxntEqPysA

**Comment by Kulu-M** [comment]
@omansak What is the best way to run your fork? I guess it is not on Nuget?

**Comment by omansak** [comment]
Fixed. Update 3.0.0
