### ISSUE TITLE
Is it possible to download the maximum resolution? 1080? 4k?

### ISSUE THREAD

**Issue by Headhuntez** [omansak/libvideo#140]
Is it possible to download videos in maximum resolution using your code? If so, tell me in detail how? I need to download a clip in 1080, but all files are saved only in 360.😢

**Comment by omansak** [comment]
Use my fork (https://github.com/omansak/libvideo)

and you can download 1080p videos without sounds

**Comment by Headhuntez** [comment]
> Use my fork
> you can download 1080p

used
i cant. end file 360. i use:
`
var youTube = YouTube.Default;
var video = youTube.GetVideo(link);
File.WriteAllBytes(@"D:\" + $"{i} {video.Title} ({video.Resolution}).{video.Format}", await video.GetBytesAsync());`

**Comment by omansak** [comment]
Fixed. Update 3.0.0
