### ISSUE TITLE
The given key was not present in the dictionary (youTube.GetVideo)

### ISSUE THREAD

**Issue by RudiHansen** [omansak/libvideo#143]
Some videos fails with this error, when i use youTube.GetVideo this link will give me that error 
 "https://www.youtube.com/watch?v=ADiio8fmOI0".

System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key was not present in the dictionary.

**Comment by omansak** [comment]
Fixed. Update 3.0.0

**Comment by RudiHansen** [comment]
Nice thanks, when will 3.0.0 be available on Nuget?

**Comment by omansak** [comment]
@RudiHansen yes i uploaded right now. Can you try and feedback me ?

**Comment by RudiHansen** [comment]
I updated my code and it is working now, so all seems good.
Thanks again.
