### ISSUE TITLE
Test version 3.0.0

### ISSUE THREAD

**Issue by omansak** [omansak/libvideo#144]
I updated new version 3.0.0 on Nuget and Github . Can anyone test it ?

**Comment by ColorTwist** [comment]
hi, 
is it the same version you updated a few days ago in another branch of yours?

**Comment by omansak** [comment]
@ColorTwist yes , just need more test different users

**Comment by ColorTwist** [comment]
For now, it seems to work well. I'll test more and update if I see any issues.
hopefully, more will assist here to test it out, after all, this library is working because of your updates.

**Comment by szblajos** [comment]
Tested! Works well! Good job, thanks @omansak !
Do you have any suggestion, how to download adaptive 720p videos with sound? They're still have no sound for me in 3.0.0

**Comment by omansak** [comment]
@szblajos just some videos downloads adaptive 720p , youtube no longer let it

**Comment by szblajos** [comment]
It's okay @omansak . I imagined that you fixed it somehow in #108 , because you closed the issue with the following text: "Fixed. Update 3.0.0"
No problem. Thanks for the NuGet package anyway!

**Comment by dinhhoi1102** [comment]
Thanks very much @omansak !, Can we decided video quality  360 or 720 ?

**Comment by omansak** [comment]
@dinhhoi1102 

Sample ;
```
var videoInfos = cli.GetAllVideosAsync(uri).GetAwaiter().GetResult();
videoInfos = videoInfos?.Where(j => j.Resolution == 360);
```
