### ISSUE TITLE
Get Only Sound from a Video

### ISSUE THREAD

**Issue by schneidermanuel** [omansak/libvideo#146]
I am Creating an Youtube to MP3 Downloader for Android in Xamarin / C#. I am using the VideoLibrary to download the Video.

So this works, I can download the Video as a mp3 file, but it also Downloads the Video. When I then Click on the .mp3 file, but it also downloads the Video. The Problem at this is, that I cant add this to a playlist, since its a Video in mp3 format, not a sound.

SO: Can I get only the Sound in VideoLibrary OR can I easy convert this Video file into a mp3 file?

Thanks for your help!!

Note: It has to work on Android (Xamarin)

**Comment by omansak** [comment]
using (var cli = Client.For(YouTube.Default))
            {
                string url = "YOUTUBE_URL";
                var videoInfos = await cli.GetAllVideosAsync(url);
                //var possibleBitrates = videoInfos.Where(i => i.AdaptiveKind == AdaptiveKind.Audio).Select(i => i.AudioBitrate);
                //var possibleResolutions = videoInfos.Where(i => i.AdaptiveKind == AdaptiveKind.Video).Select(i => i.Resolution);
                foreach (var video in videoInfos)
                {
                    if (video.AdaptiveKind == AdaptiveKind.Audio)
                    //if(video.AudioFormat == AudioFormat.Aac)
                    //if(video.AudioBitrate == 128)
                    //if(video.AdaptiveKind == AdaptiveKind.Video)
                    //if (video.Format == VideoFormat.Mp4)
                    //if (video.Resolution == 360)
                    {
                        //Other methods
                    }
                }
                //OR
                //var downloadInfo = videoInfos.Where(i => i.AudioFormat == AudioFormat.Aac && i.AudioBitrate == 128).FirstOrDefault();
                var downloadInfo = videoInfos.Where(i => i.Format == VideoFormat.Mp4 && i.Resolution == 720).FirstOrDefault(); // if 720p is possible
                string downloadUri = downloadInfo.Uri;
            }


you can gets all possible downlaod links with `GetAllVideoAsync`

**Comment by schneidermanuel** [comment]
Thanks for this, now if I click on the File, the Pop-Up player shows up and starts playing, as I wished. But Still, Music players Like "Samsung Music", VLC or "Windows groove Music" do NOT recognize this generated file. Is there anything I am doing wrong?

**Comment by Rintsi92** [comment]
You need convert file using FFMPEG, etc.. Try my new tool it's easy to look what YouTube video link contains. i think, it's can help you with your project.
https://github.com/Rintsi92/YouTubeUrlAnalyzer

if you change the file extension without converting the file, it will look like an mp3 file but not.
some music players know how to interpret a file better than others, and can play an MP3 file even if you change the file extension.

**Comment by omansak** [comment]
@BrainyXS You need convert MP3 from AAC or try download other formats
