### ISSUE TITLE
Resolution is low and appears to be read-only

### ISSUE THREAD

**Issue by pauelm** [omansak/libvideo#147]
No matter if I use my test solution or the "Valks" sample, the video is downloaded successfully, but is of poor quality. 

In the "YouTube : Video" class, there is a "Resolution" field, but it is read-only.  If this is only for retrieval methods, then where / how can you specify higher resolution version for YT video search?  

Also, are there non-YT specific video download methods in the libraries somewhere?  I reviewed the read me as well as numerous classes, but did not come across anything that looked like the correct option.  I did see the "GetAllVideosAsync" method, and wondered if I have to call that one instead, then somehow determine from the returned video collection, which video to select for download, but did not anything that looked promising.

Any ideas, or there no way to pick out higher resolution version of YT videos?  Also, are there parallel methods that are non-YT specific?

**Comment by omansak** [comment]
`        using (var cli = Client.For(YouTube.Default))
        {
            string url = "YOUTUBE_URL";
            var videoInfos = await cli.GetAllVideosAsync(url);
            //var possibleBitrates = videoInfos.Where(i => i.AdaptiveKind == AdaptiveKind.Audio).Select(i => i.AudioBitrate);
            //var possibleResolutions = videoInfos.Where(i => i.AdaptiveKind == AdaptiveKind.Video).Select(i => i.Resolution);
            foreach (var video in videoInfos)
            {
                if (video.AdaptiveKind == AdaptiveKind.Audio)
                //if(video.AudioFormat == AudioFormat.Aac)
                //if(video.AudioBitrate == 128)
                //if(video.AdaptiveKind == AdaptiveKind.Video)
                //if (video.Format == VideoFormat.Mp4)
                //if (video.Resolution == 360)
                {
                    //Other methods
                }
            }
            //OR
            //var downloadInfo = videoInfos.Where(i => i.AudioFormat == AudioFormat.Aac && i.AudioBitrate == 128).FirstOrDefault();
            var downloadInfo = videoInfos.Where(i => i.Format == VideoFormat.Mp4 && i.Resolution == 720).FirstOrDefault(); // if 720p is possible
            string downloadUri = downloadInfo.Uri;
        }`

Now, this is best solution

**Comment by omansak** [comment]
Now, we have to use `GetAllVideosAsync` cause of we reads all download links from Youtube html/js file

**Comment by pauelm** [comment]
That is what I was suspecting, and if that is the case, how do you:

1. Iterate through the results of GetAllVideosAsync (?)
2. Determine from the result set which items are "low" quality and which ones are "high" quality. (?)

**Comment by omansak** [comment]
You can iterate with `FormatCode` ' s 
Example : 137 is 1080P (no audio) ,135 is 480P muxed or 140 is only audio.

You can use that sample codes #146
