### ISSUE TITLE
Support encrypted query signatures

### ISSUE THREAD

**Issue by jamesqo** [omansak/libvideo#15]
Right now we don't support encrypted signatures in the URL query when extracting the link from YouTube. This can lead to 403 errors when downloading the video, which could be the cause of #8.

YoutubeExtractor already [handles this problem](https://github.com/flagbug/YoutubeExtractor/blob/master/YoutubeExtractor/YoutubeExtractor/DownloadUrlResolver.cs#L28-L51), so it shouldn't be too hard to refactor the code from there and implement this.

**Comment by i3arnon** [comment]
@jamesqo Just a note about the implementation: 
YE enables getting all the urls encrypted (by passing `false`) and explicitly decrypting specific ones.
This is a good paradigm as it can improve performance significantly.

**Comment by terrybrash** [comment]
Currently porting my application over to libvideo and ran into this problem.  How's progress?  I can work on it if you haven't started yet.

**Comment by jamesqo** [comment]
@inlinevoid Working on it, but I should be finished within a day or two. I'll let you know when I've made the change.

Thanks for the offer, by the way!

**Comment by jamesqo** [comment]
This is finally supported: 7dadee8. Unfortunately I renamed some of the classes in the new version as well ([changelog](https://github.com/jamesqo/libvideo/blob/master/changelog.md)), so you may have to do a find-and-replace for them.

Thanks for your support, let me know if you guys have any problems!
