### ISSUE TITLE
Memory usage accumulation

### ISSUE THREAD

**Issue by henriquecpp** [omansak/libvideo#152]
I have an application (desktop) that reproduces various sounds, but each time I execute the method below, the program accumulates space in memory. How can I solve this?

```cs
public static string GetURI(string url)
{
    YouTube yt = new YouTube();            

    string uri = yt.GetAllVideos(url).FirstOrDefault(v => v.AudioBitrate >= 96 && v.AdaptiveKind == AdaptiveKind.Audio).Uri;    
    yt = null;
    return uri;
}
```

**Comment by omansak** [comment]
```
        public static string GetURI(string url)
        {
            using (var cli = Client.For(YouTube.Default))
            {
                return cli.GetAllVideos(url).FirstOrDefault(v => v.AudioBitrate >= 96 && v.AdaptiveKind == AdaptiveKind.Audio)?.Uri;
            }
        }
```

**Comment by HenriqueMarino** [comment]
Thanks for answering

It is strange, but even with "using" to discard the object after use, it still continues with the problem. See the print of the memory usage graph:

![image](https://user-images.githubusercontent.com/38007771/77229843-e887a600-6b6e-11ea-8fac-18fda37ba83e.png)

This represents the first two times that I called the method. See that it is like a ladder, and continues at this rate each time the method is called.

**Comment by omansak** [comment]
Outdated
