### ISSUE TITLE
Invalid request URI error

### ISSUE THREAD

**Issue by vincetota** [omansak/libvideo#155]
Hi!
Thanks for your great library.
Today, it appears this error when I try to download a video:
"**_An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set._**"
I did not change anything in the code.... I'm just using these simple lines:

  ```
Dim DestFile1 As String = GetPath() & "\Videos\" & Filename & ".mp4"
Dim video1 = YouTube.Default.GetVideo("https://www.youtube.com/watch?v=mlBIpwtNxxE")
 File.WriteAllBytes(DestFile1, video1.GetBytes)
```

I tried to use http instead of https, but same issue.

Please can you help me to fix?

Thanks a lot!

**Comment by JOBBIN9422** [comment]
I have occasionally run into the same issue when downloading videos in my project. I can provide more info if necessary.

**Comment by ReflexLevel0** [comment]
Same thing is happening to me with function youtube.GetAllVideos(string link). For some videos it works and for some it doesn't when before it used to work for all videos.

**Comment by JOBBIN9422** [comment]
I can confirm the issue that @ReflexLevel0 is running into, it seems to be arbitrarily failing on certain videos.

**Comment by JOBBIN9422** [comment]
Posting a stack trace for reference:
`System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsync(String requestUri)
   at VideoLibrary.DelegatingClient.GetStringAsync(String uri)
   at VideoLibrary.YouTubeVideo.DecryptAsync(String uri, Func`1 makeClient)
   at VideoLibrary.YouTubeVideo.GetUriAsync(Func`1 makeClient)
   at VideoLibrary.VideoClient.GetBytesAsync(Video video)
   at VideoLibrary.Video.GetBytesAsync()`

**Comment by nlogozzo** [comment]
Can confirm. It's happening on most videos, even ones that have recently worked before

**Comment by ghost** [comment]
Youtube is messing around thats why "VideoLibrary" is not working on all vides any more

**Comment by omansak** [comment]
Can you guys try again ?

**Comment by vincetota** [comment]
> Can you guys try again ?

For this video https://www.youtube.com/watch?v=mlBIpwtNxxE still same error.
Do I need to update the package? Or continue to use version 3.0?
Thank you!

**Comment by omansak** [comment]
@vincetota i pushed a little change to github .

**Comment by vincetota** [comment]
> @vincetota i pushed a little change to github .

OK! it seems to work very well!

**Comment by wesbyte** [comment]
@omansak Could you please update the NuGet?

**Comment by ghost** [comment]
It works thank you

**Comment by omansak** [comment]
@wesbyte i updated on nuget.

**Comment by wesbyte** [comment]
@omansak Works great! Many thanks.

**Comment by nlogozzo** [comment]
All problems solved. Thanks!

**Comment by omansak** [comment]
#157
