### ISSUE TITLE
An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.

### ISSUE THREAD

**Issue by MNutshell** [omansak/libvideo#157]
Just started getting this issue on some YT URLS - i noticed this was reported long ago.

I had been using this library for a while and just started getting the error above
URL tested: https://www.youtube.com/watch?v=02LSFTdC5UE 

using 3.0.0 

Thanks

**Comment by omansak** [comment]
Please try again with 3.0.1

**Comment by MNutshell** [comment]
I did do a pull - and build - and it is showing 3.0.0 - 

but - wala - it does seem to be functioning now - sorry for the interruptino.
