### ISSUE TITLE
VideoLibrary Xamarin Forms

### ISSUE THREAD

**Issue by MarvinBitzer1408** [omansak/libvideo#158]
Hello I have a problem with downloading a video in XamarinForms with the nuget Video Library.
I want to download it but i dont know how i get my path in xamarinforms and in which way I connect the path with  File.writeAllBytes(path + video.FullName, video.GetBytes()). ??
or this way :  File.writeAllBytes(path +"/"+ video.FullName, video.GetBytes()). ??

Or can i download the video in my andorid Download file?
My Problem is i cant find the video on my phone because i cant select the right path

using VideoLibrary;

void SaveVideoToDisk(string link)
{
    var youTube = YouTube.Default; // starting point for YouTube actions
    var video = youTube.GetVideo(link); // gets a Video object with info about the video
    File.WriteAllBytes(@"C:\" + video.FullName, video.GetBytes());
}

**Comment by omansak** [comment]
test. it works
