### ISSUE TITLE
Issue when trying to get URI

### ISSUE THREAD

**Issue by AnesHamdani08** [omansak/libvideo#159]
Most of youtube videos return error 
An Invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set
Why is that happening?
here is a video that return this error : https://www.youtube.com/watch?v=Axq1FHwFMrQ

**Comment by dmanolac** [comment]
I also have this issue, with URL: https://youtu.be/wYeFAlVC8qU?list=RDwYeFAlVC8qU

**Comment by JOBBIN9422** [comment]
Out of curiosity, what version of the library are you guys running? A similar issue popped up in 3.0.0 and was fixed in 3.0.1.

**Comment by dmanolac** [comment]
I had 3.0.0. The upgrade to 3.0.1 did the tricks. Thanks for pointing that out.

**Comment by AnesHamdani08** [comment]
Yep i was on 3.0.0
