### ISSUE TITLE
System.InvalidOperationException: 'Sequence contains no elements'

### ISSUE THREAD

**Issue by FutureDeve** [omansak/libvideo#161]
Not working at the moment after the you supply a valid uri at this part " var video = youtube.GetVideo(uri);" you get the invalid exception.

Please help.

Thank you

**Comment by bakyard** [comment]
Same here

**Comment by vincetota** [comment]
Same issue for me...

**Comment by omansak** [comment]
Fixed also updated Nuget Package

**Comment by FutureDeve** [comment]
Cheers

**Comment by noletoft** [comment]
its only me or this issue is back?
