### ISSUE TITLE
Download a playlist

### ISSUE THREAD

**Issue by nicolapreda** [omansak/libvideo#164]
Good morning, I would like to know if with this NuGet pack it is also possible to download entire playlists from youtube. If you could help me with the code? thank you very much.
With this code i can only download videos from youtube in .mp3 or .mp4: 

using (FolderBrowserDialog fdb = new FolderBrowserDialog() { Description = "Seleziona la cartella di destinazione del download" }) 
            {
                if(fdb.ShowDialog() == DialogResult.OK)
                {
                    GetTitle();
                    lblInfo.Visible = true;
                    SongDownload.Visible = true;

                    lblInfo.Text = "Download playlist in corso...";
                    lblInfo.ForeColor = Color.Orange;
                    
                    var youtube = YouTube.Default;
                    var video = await youtube.GetVideoAsync(textBox1.Text);
                    File.WriteAllBytes(fdb.SelectedPath + @"\" + video.FullName, await video.GetBytesAsync());

                    var inputFile = new MediaToolkit.Model.MediaFile { Filename = fdb.SelectedPath + @"\" + video.FullName };
                    var outputFile = new MediaToolkit.Model.MediaFile { Filename = $"{fdb.SelectedPath + @"\" + video.FullName}.mp3" };

                    using (var enging = new Engine())
                    {
                        enging.GetMetadata(inputFile);
                        enging.Convert(inputFile, outputFile);
                    }

                    if (FormatDrum == true)
                    {
                        File.Delete(fdb.SelectedPath + @"\" + video.FullName);
                    }
                    else
                    {
                        File.Delete($"{fdb.SelectedPath + @"\" + video.FullName}.mp3");
                    }
                    

                    lblInfo.Text = "Download playlist completato!";
                    lblInfo.ForeColor = Color.Green;
                }
                else
                {
                    MessageBox.Show("Errore nel download","Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }

        void GetTitle()
        {
            WebRequest request = HttpWebRequest.Create(textBox1.Text);
            WebResponse response;
            response = request.GetResponse();
            StreamReader reader = new StreamReader(response.GetResponseStream());
            string readtitle = reader.ReadToEnd();
            int text = readtitle.IndexOf("<title>") + 7;
            int strings = readtitle.Substring(text).IndexOf("</title>");
            string substring = readtitle.Substring(text, strings);
            SongDownload.Text = (substring);
        }

**Comment by nlogozzo** [comment]
Look @ #156
