### ISSUE TITLE
Videos are unavailable, How use proxy?

### ISSUE THREAD

**Issue by AbbasBHF** [omansak/libvideo#165]
Hey
When I call getAllVideos from localhost for some videos, I can get videos.
But when I call it from a server that is in Germany, videos are unavailable.
I had this problem with YoutubeExplode.

1. Proxy can solve this problem?
2. If 1 == true then how I can use proxy with this library?

**Comment by adlucas** [comment]
Yes I have the same issue.
When I do :
var vid = youtube.GetVideo("https://www.youtube.com/watch?v=x5uF0-7M9vk");

it throws an exception.

On may 2020 it has been working.

How can I solve?

**Comment by omansak** [comment]
@adlucas update nuget or build files

**Comment by MartelSimon** [comment]
Same Issue

**Comment by HopInTheCloud** [comment]
Same issue and I am on version 3.1.9

**Comment by omansak** [comment]
i will check that
