### ISSUE TITLE
Title of each video is "YouTube"

### ISSUE THREAD

**Issue by Ricomitdreio** [omansak/libvideo#166]
If I try to download a youtube video then I get only the Title "YouTube" and FullName "YouTube.mp4" but the video is the right one and I can download this. 
It was working very good till now.
![image](https://user-images.githubusercontent.com/39564073/86266281-43488900-bbc5-11ea-96dc-e32630c966cf.png)

**Comment by AnesHamdani08** [comment]
I get that issue too
