### ISSUE TITLE
The given key was not present in the dictionary

### ISSUE THREAD

**Issue by Moooog** [omansak/libvideo#167]
`YouTubeVideo vid = YouTube.Default.GetVideo(GetURL);`

Result:
![image](https://user-images.githubusercontent.com/25987993/87462462-e1960f00-c607-11ea-982b-94b19a9f46a8.png)

**Comment by omansak** [comment]
Please update lase version

**Comment by Moooog** [comment]
> Please update lase version

still the same issue.
