### ISSUE TITLE
Could not find signature decipherer definition body...

### ISSUE THREAD

**Issue by vincetota** [omansak/libvideo#169]
Today I receive this error when I try to download a video: "Could not find signature decipherer definition body. Please report this issue to us."

Please can you check?
Thanks a lot!

**Comment by nlogozzo** [comment]
Getting the same error....

**Comment by ColorTwist** [comment]
Same here.

**Comment by nlogozzo** [comment]
Here's the full error i'm getting. Happens with every video i try to download
![image](https://user-images.githubusercontent.com/17648453/88110616-7e155f80-cb7a-11ea-8195-8aab26f44607.png)

**Comment by omansak** [comment]
I am looking now
