### ISSUE TITLE
HttpClient hangs with large videos

### ISSUE THREAD

**Issue by jamesqo** [omansak/libvideo#17]
Try downloading [this](https://www.youtube.com/watch?v=kkoiLQO5JGo) 1.2 hour long video. [It will hang.](https://www.reddit.com/r/csharp/comments/3lk7yi/libvideo_for_youtube_progress_update/cv8vjj7)

If you open Task Manager (or the equivalent on Mac/Linux) while downloading it, you'll notice that the memory usage starts crawling up and eventually stagnates at around 1 GB. Closing the process drastically lowers the memory usage.

---

**To fix:** Introduce some kind of streaming API that lets you download a few chunks at a time? We do support reading a video as a `Stream` currently, through `Stream()` and `StreamAsync()`, but it turns out it's just [a fake `MemoryStream` wrapper](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpContent.cs#L278-L279) over an existing `byte[]`. Basically we still download the video whole, and then process it.

**Comment by jamesqo** [comment]
Removed the `[todo]` label as we don't have a concrete solution yet.

**Comment by bigworld12** [comment]
@jamesqo how do you get the bytes of the video? do you use a stream to read them ?
