### ISSUE TITLE
Could not find signature decipherer definition body...

### ISSUE THREAD

**Issue by vincetota** [omansak/libvideo#170]
Today I'm experiencing again the error "Could not find signature decipherer definition body...contact us". The same of 6 days ago...
Please can you check?

Thanks a lot!

**Comment by Jack-Paul** [comment]
Yes, facing same problem, youtube has modified something.

**Comment by tiagogenuino** [comment]
I am also having the same problem when downloading with the IsEncrypted property as true. When the property is not set to true it works normally.

**Comment by ColorTwist** [comment]
Same here like a few days ago.

**Comment by omansak** [comment]
I am looking now

**Comment by omansak** [comment]
can you guys try last commit ?

**Comment by ColorTwist** [comment]
Did a short test, seems to be working! Well Done!

**Comment by gdmarconetto** [comment]
Hi, same problem, but It's working now! Can you please create a new version of NuGet package ? It will be awesome

**Comment by omansak** [comment]
Nuges has updated

**Comment by tiagogenuino** [comment]
Testing here, it worked again. thank you very much.
