### ISSUE TITLE
Youtube API Key - Need help!

### ISSUE THREAD

**Issue by Ricomitdreio** [omansak/libvideo#173]
I have a question about youtube api key. 
After some downloads I get a limit message and then I cant download more videos for some hours. I can solve this problem if I use an api key from the youtube developer page. 
But I don't know, how I can use the key with libvideo. 
Can you help me, please?

**Comment by Donaut** [comment]
i think if you use an api key you still got a daily limit. I don't think libvideo video support api key or oauth in any way.

**Comment by Ricomitdreio** [comment]
Okay :(
