### ISSUE TITLE
Not all video resolution ara available

### ISSUE THREAD

**Issue by gdmarconetto** [omansak/libvideo#174]
Hi all,
i have a strange problem with one YouTube video.

For an application i need the direct uri to the video to play it, so here is what i'm doing:

```
List<YouTubeVideo> videos = YouTube.Default
                    .GetAllVideos(url)
                    .ToList();

 if (videos != null && videos.Count > 0)
 {
      videos = videos
              .Where(v => v.Resolution <= Configuration.VIDEO_WANTED_RESOLUTION)
              .OrderByDescending(v => v.Resolution)
              .ToList();

              if (videos.Count > 0)
             {
                  return videos.FirstOrDefault();
             }
  }

```
Than i can this to get the Uri:
`
video.Uri;
`

With [this](https://www.youtube.com/watch?v=F2d2hEM1N6k&feature=youtu.be) YouTube video i get that for some resolution (like 720p) ContentLenght = 0 and Uri return a error page.

It's normal ? Depends on the video ? This some day ago working perfectly. 

Thanks!

**Comment by banderberg** [comment]
You can also specify the query string param vq=hd1080 for example to get 1080p, and the video downloaded is the same size with or without it, and is clearly NOT 1080p.

**Comment by omansak** [comment]
Thank you for  feedback.
i will look this issue as soon

**Comment by HaseebUllahAbbasi** [comment]
@omansak  Have you set your own resolution , did you succeed?

**Comment by christopher-nzcs** [comment]
> @omansak Have you set your own resolution , did you succeed?

@HaseebUllahAbbasi, Yeah. you just have to add `&vq=hd1080` to the end of the url.
Here is a link showing how you can change the resolution/fullscreen via the URL: [Here](https://www.cnet.com/how-to/how-to-link-to-full-screen-hd-video-in-youtube/)

**Comment by omansak** [comment]
please test #201

**Comment by omansak** [comment]
added new formats
