### ISSUE TITLE
still getting 'sequence contains no elements' error

### ISSUE THREAD

**Issue by derekj-s** [omansak/libvideo#176]
This happens randomly, it isn't a consistent error. I notice it happens when I download more than 5 videos in a row.

The console outputs this: 

Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
An exception of type 'System.InvalidOperationException' occurred in mscorlib.dll but was not handled in user code
Sequence contains no elements

When trying to call:             var vid = youtube.GetVideo(uri);

**Comment by derekj-s** [comment]
fixed this with a simple try-catch statement

**Comment by omansak** [comment]
Can you test last commit ?
