### ISSUE TITLE
Sequence contains no elements when downloading

### ISSUE THREAD

**Issue by tesses50** [omansak/libvideo#177]
I use wii-linux-ngx and this library worked on my wii yesterday

But i still think the wii part is irrelevant to this issue

**Comment by Khirath-bit** [comment]
Got the same issue here. It worked on my windows computer yesterday.

**Comment by Disseldoof** [comment]
Hey,
got the same issue.
Can't exectuce GetAllVideos or GetVideo.
ErrorMsg: Sequence contains no elements

**Comment by noletoft** [comment]
Same here, it seems to be a recorrent issue raised here couple of months ago : https://github.com/omansak/libvideo/issues/161

**Comment by vincetota** [comment]
Same issue here...

**Comment by derekj-s** [comment]
same here, this issue occurred randomly every once in a while, so a simple catch statement was able to fix it. Now it is consistently getting this error, so  .GetVideo does not work at all. There is a 0 success rate, not sure what triggered this issue. It's probably from Youtubes end. Omansak please fix :(

**Comment by gdmarconetto** [comment]
Same here

**Comment by ugurisik** [comment]
same issue here

**Comment by omansak** [comment]
Can you test last commit ?

**Comment by vincetota** [comment]
It works now for me.
Thank you Omansak!

**Comment by alibalci7** [comment]
it still doesnt work for me 
what should i do for making it worked?

**Comment by derekj-s** [comment]
how do i test the last commit if I installed the package using NuGet?

**Comment by omansak** [comment]
@derekj-s Yes, i has just updated on nuget

**Comment by noletoft** [comment]
Working again! Thanks Omansak
