### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by KevinDeery** [omansak/libvideo#183]
Hi , 

Ive been using this for a long time in my movie app and recently im getting "Sequence contains no elements", this occurs in the basic sample. Maybe YouTube have changes something in there HTML markup

`
 try
 {
     string uri = "https://www.youtube.com/watch?v=vPto6XpRq-U";
     var youTube = YouTube.Default;
     var video = youTube.GetVideo(uri);
 }
 catch (Exception ex)
 {
      Debug.WriteLine("Trailer Search: " + ex.Message.ToString());
 }
`

**Comment by omansak** [comment]
`vPto6XpRq-U` is unavailable on YT
