### ISSUE TITLE
Player json has no found.

### ISSUE THREAD

**Issue by arogerm** [omansak/libvideo#186]
Dear all
When i try to download a video a recived a exception Player json has no found.
var youTube = YouTube.Default;// starting point for YouTube actions
var video = youTube.GetVideo("https://www.youtube.com/watch?v=mCeF-IF7JMg"); 
which could be the mistake in my code?

**Comment by omansak** [comment]
i guess its seem like a bug

**Comment by arogerm** [comment]
Thanks for your fast reply

**Comment by arogerm** [comment]
For your information
I think that it's a malformed Json
If you change the funcion ParsePlayerJson(string source) removing \r\n at start an change ytInitialPlayerPattern excluding <script match then works


private string ParsePlayerJson(string source)
{
	**source = source.Replace(@"\u0026", "&").Replace("\n", string.Empty).Replace("\r", string.Empty).Replace("var ", "\r\nvar ");**
	string playerResponseMap = null, ytInitialPlayerPattern = @"<script .*>\s*var\s*ytInitialPlayerResponse\s*=\s*(\{\""responseContext\"".*\});<\/script>", ytWindowInitialPlayerResponse = @"\[\""ytInitialPlayerResponse\""\]\s*=\s*(\{.*\});", **ytPlayerPattern = @"ytplayer\.config\s*=\s*(\{\"".*\""\}\});";**
	Match match;
	if ((match = Regex.Match(source, ytPlayerPattern)).Success && Json.TryGetKey("player_response", match.Groups[1].Value, out string json))
	{
		playerResponseMap = Regex.Unescape(json);
	}
	**ytInitialPlayerPattern = @"\s*var\s*ytInitialPlayerResponse\s*=\s*(\{\""responseContext\"".*\})";**
	if (string.IsNullOrWhiteSpace(playerResponseMap) && (match = Regex.Match(source, ytInitialPlayerPattern)).Success)
	{
		playerResponseMap = match.Groups[1].Value;
	}
	if (string.IsNullOrWhiteSpace(playerResponseMap) && (match = Regex.Match(source, ytWindowInitialPlayerResponse)).Success)
	{
		playerResponseMap = match.Groups[1].Value;
	}
	if (string.IsNullOrWhiteSpace(playerResponseMap))
	{
		throw new UnavailableStreamException("Player json has no found.");
	}
	return playerResponseMap;
}

**Comment by omansak** [comment]
@arogerm ty for solution. can you test last changes?

**Comment by arogerm** [comment]
Dear omansak
now work fine.
Thanks
