### ISSUE TITLE
Erro resolution, the resolution not exist in video

### ISSUE THREAD

**Issue by AndreZila01** [omansak/libvideo#187]
Hey everyone,

I have one problem in my project and i cann't "jump" this step. If i try download [one video](https://www.youtube.com/watch?v=sv5_2_H9M3Q), for example and the project give my 'Object reference not set to an instance of an object.'.

At the moment i have this code: 

	```using (var cli = Client.For(YouTube.Default)){
		try
		{
			link = txt.Text;
			var videoInfos = await cli.GetAllVideosAsync(link);
			try
			{


				var downloadInfo = videoInfos.Where(i => i.Format == VideoFormat.Mp4 && (i.Resolution == 	int.Parse(cboResolucao.Text))).FirstOrDefault();//cboResolucao=720;
				downloadUri = downloadInfo.Uri;//<-Error there 

				File.WriteAllBytes(textBox1.Text + @"\" + downloadInfo.FullName, downloadInfo.GetBytes());//paths where i save file.
			}catch{}
		}catch{}
	}´´´


Thanks very much

**Comment by omansak** [comment]
Hi;
Thank you for issue. your related video have {144,240,360,480}p resolutions. what is the ` int.Parse(cboResolucao.Text)` code's result ?

**Comment by AndreZila01** [comment]
![image](https://user-images.githubusercontent.com/56931353/104644603-dd75a780-56a5-11eb-8ee9-9f05aa0a5d1d.png)

**Comment by omansak** [comment]
your resulution is hard coded values ?

**Comment by AndreZila01** [comment]
?

**Comment by AndreZila01** [comment]
#148
