### ISSUE TITLE
Feature Request: add "videoDetails.author" and "videoDetails.lengthSeconds" as additional information

### ISSUE THREAD

**Issue by DanCooper** [omansak/libvideo#190]
Hello

Please add the information "DurationInSeconds" (videoDetails.lengthSeconds) and "Author" (videoDetails.author). This information is very useful for filtering videos.

**Comment by omansak** [comment]
this is a great idea, i will work on this as soon

**Comment by omansak** [comment]
may you test last commit 82f24c09e3cccb577fa9887e5d091abf5d86fce6?

**Comment by DanCooper** [comment]
Thank you! I'lkl test it later today and do a feedback.

**Comment by DanCooper** [comment]
So, 3 days later I've found the time to test (sorry for the delay). And it works as expected and great! Thank you!
