### ISSUE TITLE
Cannot collect all resolutions, ...

### ISSUE THREAD

**Issue by AndreZila01** [omansak/libvideo#198]
Hey programmers, 

i have one problem of to collect all resoltion of video, i use this source:

```
link = "https://youtu.be/IYcwcv5chH4"//exemple link video, ...
var videoInfos = await cli.GetAllVideosAsync(link);
var resolutions = videoInfos.Where(j => j.AdaptiveKind == AdaptiveKind.Video).Select(j => j.Resolution);
```

And collect Null, ... 

![image](https://user-images.githubusercontent.com/56931353/113491682-790afd00-94ca-11eb-9f31-a8aba0bc5362.png)

if you have a solution, please help me.

**Comment by omansak** [comment]
![image](https://user-images.githubusercontent.com/14445821/113575589-c4d2b900-9626-11eb-89cc-1bbacb08d29c.png)

this is valid code for me. 

```
  var cli = Client.For(YouTube.Default);
  var link = "https://youtu.be/IYcwcv5chH4";
  var videoInfos = cli.GetAllVideosAsync(link).GetAwaiter().GetResult();
  var resolutions = videoInfos.Where(j => j.AdaptiveKind == AdaptiveKind.Video).Select(j => j.Resolution);
  var foo = string.Join(",", resolutions);
```

**Comment by AndreZila01** [comment]
One question omanask how i can collect 60fps in video, "1080p60".

**Comment by AndreZila01** [comment]
The code not worked: 
![image](https://user-images.githubusercontent.com/56931353/115052556-fb85ba80-9ed5-11eb-84c4-aa7f6a853fa1.png)

**Comment by omansak** [comment]
> One question omanask how i can collect 60fps in video, "1080p60".

you can use FPS property in 3.1.2
