### ISSUE TITLE
No more audio

### ISSUE THREAD

**Issue by HiImLesic** [omansak/libvideo#199]
Im using libvideo as a way to download audio files.
However, since a few days, .GetAllVideos wont give me any audio format anymore.
This is what I have been using since a couple of years and its been working quite well:
```
var youtube = YouTube.Default;
var videos = youtube.GetAllVideos("https://www.youtube.com/watch?v=cK8XNDpN6-Q");
var audio = videos
    .Where(v => v.AudioFormat == AudioFormat.Aac && v.AdaptiveKind == AdaptiveKind.Audio)
    .ToList();
```

However in this case, audio is an empty list now.
In fact, videos is already an empty list...

**Comment by omansak** [comment]
#201

**Comment by omansak** [comment]
please test 3.1.1 on github and nuget
