### ISSUE TITLE
I am getting error net_http_message_not_success_statuscode in Windows Phone 8.1

### ISSUE THREAD

**Issue by iamchandreshk** [omansak/libvideo#20]
I am getting error net_http_message_not_success_statuscode in Windows Phone 8.1, how to resolve it ?

**Comment by jamesqo** [comment]
Hi, I'd be glad to help! Exactly what status code are you getting? Can you copy-paste the stack trace you're getting/some sample code so I can reproduce the issue? Thanks.

**Comment by iamchandreshk** [comment]
Hi, Thanks for the response.

Here is an Error : net_http_message_not_success_statuscode
and Here is a Code :

```
public async static Task<bool> GetAvailableFormats(string id)
        {
            bool isSuccess = false;
            try
            {
                var GetVideos = await YouTube.Default.GetAllVideos("www.youtube.com/watch?v=" + id);
            }
            catch
            {
                isSuccess = false;
            }
            return isSuccess;
        }
```

Here is the stack trace :

> {System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at VideoLibrary.YouTube.<GetAllVideosAsync>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at VideoLibrary.ServiceBase`1.<GetAllVideosAsync>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at VideoLibrary.ServiceBase`1.GetAllVideos(String videoUri)
>    at YouTubeDownload.DataLayer.YoutubeData.GetAvailableFormats(String id)}

**Comment by iamchandreshk** [comment]
Dear jamesqo,

is there any update?

**Comment by jamesqo** [comment]
@chandresh29 Hey! Sorry, been a bit busy recently so I didn't have the chance to reply :wink: Anyway, I've been trying to reproduce your error, but all the videos I've tested seem to work fine. Could you give me the URL of a video that's troubling you?

**Comment by iamchandreshk** [comment]
That was the random link, can you share that code with me ?

my email id is chandresh.cmk@hotmail.com

**Comment by iamchandreshk** [comment]
This issue is not resolved yet.

**Comment by jamesqo** [comment]
@chandresh29 Sorry, I had assumed you weren't active.

I'm running the [unit tests](https://github.com/jamesqo/libvideo/blob/master/tests/Core/Core/UnitTests.cs) against a couple of videos and they seem to be running fine, could you share the random link so I can test for it myself?

Thanks.

**Comment by Black-Platypus** [comment]
I am getting a `System.Net.Http.HttpRequestException`: "Response status code does not indicate success: 403 (Forbidden) - might that be related?

It happens while calling `.GetBytes()` on a video that would cause the application to fail with an unhandled exception caused by #27 in 1.3.3
(for example https://www.youtube.com/watch?v=DW4f1x6IQ9o)

However, I can query the `.FullName`, for example, no problem.

Weirdly, the Visual Studio debugger highlights lines that come before the actual `.GetBytes()`... 
I commented some out, removed some... every time, something further back is highlighted. Ended up having a `MessageBox.Show("test");` before the call. That runs fine, and as soon as the call happens, the MessageBox.Show gets highlighted showing a `System.Net.Http.HttpRequestException` error :D ...seems like a Visual Studio error.

Anyway, in case it helps, here are the details:
`
System.Net.Http.HttpRequestException was unhandled
  HResult=-2146233088
  Message=Der Antwortstatuscode gibt keinen Erfolg an: 403 (Forbidden).
  Source=mscorlib
  StackTrace:
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei VideoLibrary.VideoClient.<GetBytesAsync>d__10.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei VideoLibrary.Video.<GetBytesAsync>d__11.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
       bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       bei VideoLibrary.Video.GetBytes()
       bei Ben_s_Youtube_Downloader.Form1.dlsingleb_Click(Object sender, EventArgs e) in D:\visual studio 2015\Projects\Ben's Youtube Downloader\Ben's Youtube Downloader\Form1.cs:Zeile 550.
       bei System.Windows.Forms.Control.OnClick(EventArgs e)
       bei System.Windows.Forms.Button.OnClick(EventArgs e)
       bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       bei System.Windows.Forms.Control.WndProc(Message& m)
       bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
       bei System.Windows.Forms.Button.WndProc(Message& m)
       bei System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       bei Ben_s_Youtube_Downloader.Program.Main(String[] args) in D:\visual studio 2015\Projects\Ben's Youtube Downloader\Ben's Youtube Downloader\Program.cs:Zeile 27.
       bei System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       bei System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext activationContext, String[] activationCustomData)
       bei Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssemblyDebugInZone()
       bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       bei System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
`

**Comment by iamchandreshk** [comment]
Wht this is closed without reslving?
