### ISSUE TITLE
Error getting ANY videos or audios from YT

### ISSUE THREAD

**Issue by wolfSYS** [omansak/libvideo#200]
I had to see that all of a sudden your library stopped working.  It is not any longer possible to obtain any files from youtube.

![yt-lib-not-any-files](https://user-images.githubusercontent.com/15673259/114711841-b58ef200-9d2f-11eb-8642-2c9217e7afb4.png)

Both **GetAllVideosAsync()** and **GetVideoAsync()** return NULL für _every_ single YT ID.

**Comment by RK4444** [comment]
Yeah, the same problem here

**Comment by wolfSYS** [comment]
We need the possibility to pass **HttpClient** to the YoutubeClient.  In **HttpClient** we could set the **CONSENT cookie** for Youtube like this:

            Uri uri = new Uri("https://www.youtube.com");
            HttpClientHandler handler = new HttpClientHandler();
            handler.CookieContainer = new CookieContainer();
            handler.CookieContainer.Add(uri, new Cookie("CONSENT", "YES+cb", "/", "youtube.com"));
            HttpClient hc = new HttpClient(handler);

            // that would be needed:
            YoutubeClient youtube = new YoutubeClient(hc);_

**Comment by omansak** [comment]
please test #201

**Comment by omansak** [comment]
please test 3.1.1 on github and nuget

**Comment by wolfSYS** [comment]
solved with ver 3.1.1
thx a lot!
