### ISSUE TITLE
Test - Cookie consest

### ISSUE THREAD

**Issue by omansak** [omansak/libvideo#201]
class MyHandler
    {
        public HttpMessageHandler handler = null;
        public CookieContainer cookieContainer = new CookieContainer();
        public HttpMessageHandler GetHandler()
        {
            if (handler == null)
            {
                cookieContainer.Add(new Cookie("CONSENT", "YES+cb", "/", "youtube.com"));
                handler = new HttpClientHandler
                {
                    UseCookies = true,
                    CookieContainer = cookieContainer
                };
            }

            return handler;
        }
    }
    class MyYouTube : YouTube
    {
        public MyHandler handler = new MyHandler();
        protected override HttpClient MakeClient(HttpMessageHandler handler)
        {
            return base.MakeClient(handler);
        }

        protected override HttpMessageHandler MakeHandler()
        {
            return handler.GetHandler();
        }
    }
    class CustomYoutubeClient : VideoClient
    {
        public MyHandler handler = new MyHandler();
        protected override HttpClient MakeClient(HttpMessageHandler handler)
        {
            return base.MakeClient(handler);
        }

        protected override HttpMessageHandler MakeHandler()
        {
            return handler.GetHandler();
        }
    }
    class Test
    {
        public void Run()
        {
            var youtube = new MyYouTube();
            LogCookie(youtube.handler.cookieContainer);
            var foo1 = youtube.GetAllVideosAsync("https://www.youtube.com/watch?v=qK_NeRZOdq4").GetAwaiter().GetResult();
            LogCookie(youtube.handler.cookieContainer);
            var video = foo1.ToList().FirstOrDefault();
            // Custom Youtube
            var byte1 = video.GetBytesAsync().GetAwaiter().GetResult();
            LogCookie(youtube.handler.cookieContainer);
            // Custom Client
            var client = new CustomYoutubeClient();
            var byte2 = client.GetBytesAsync(video).GetAwaiter().GetResult();
            LogCookie(youtube.handler.cookieContainer);
        }
        private void LogCookie(CookieContainer container)
        {
            var responseCookies = container.GetCookies(new Uri("https://www.youtube.com"));
            foreach (Cookie cookie in responseCookies)
                Console.WriteLine(cookie.Name + ": " + cookie.Value);
        }
    }

Some videos has error but i can not get any error.  If u have any error video , please try this give me result

**Comment by wolfSYS** [comment]
Hmm didn't solve it.  Sample console app

using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using VideoLibrary;

namespace ConsoleTestWorkAroundYT
{	class MyHandler
	{
		public HttpMessageHandler GetHandler()
		{
			var cookieContainer = new CookieContainer();
			cookieContainer.Add(new Cookie("CONSENT", "YES+cb", "/"));
			var handler = new HttpClientHandler
			{
				UseCookies = true,
				CookieContainer = cookieContainer
			};
			return handler;
		}
	}

	class MyYouTube : YouTube
	{
		protected override HttpClient MakeClient(HttpMessageHandler handler)
		{
			return base.MakeClient(handler);
		}

		protected override HttpMessageHandler MakeHandler()
		{
			return new MyHandler().GetHandler();
		}
	}

	class CustomYoutubeClient : VideoClient
	{
		protected override HttpClient MakeClient(HttpMessageHandler handler)
		{
			return base.MakeClient(handler);
		}

		protected override HttpMessageHandler MakeHandler()
		{
			return new MyHandler().GetHandler();
		}
	}

	public class Program
	{
		private static void Main(string[] args)
		{
			using (var cli = Client.For(YouTube.Default))
			{
				var foo = cli.GetAllVideosAsync("https://www.youtube.com/watch?v=qK_NeRZOdq4").GetAwaiter().GetResult();

				if (foo.ToList().Count > 0)
					Console.WriteLine("got something.");
				else
					Console.WriteLine("nothing in here.");
			}
			Console.ReadKey();
		}
	}
}

always returns the same error.

**Comment by wolfSYS** [comment]
Thank you for your quick response.
Unfortunately this doesn't work for me.  Created a little console app like above but setting breakpoints in the override methods never ever get fired and **cli.client.handler.CookieContainer** does not contain "CONSENT" nor "YES+cb".

**Comment by omansak** [comment]
> Thank you for your quick response.
> Unfortunately this doesn't work for me. Created a little console app like above but setting breakpoints in the override methods never ever get fired and **cli.client.handler.CookieContainer** does not contain "CONSENT" nor "YES+cb".

sorry my bad i will back soon :D

**Comment by akaelin** [comment]
@omansak
I managed to solve the error caused by the consent page.

if the request is coming back with the consent page, i parse the "Agree" Form und make another post with the hidden Fields sent as FormUrlEncodedContent. The returned Request is then the expected Video which allows the code to proceed as normal.

![ConsentPage](https://user-images.githubusercontent.com/4598105/114928179-97f68100-9e32-11eb-9167-0d715221b4f4.PNG)


I Put the code inside the Class "Client" (Quick & Dirty):
I used the nuget Package "**HtmlAgilityPack**" to parse the html.

private async Task<string> SourceFactory(string address) {

            HttpResponseMessage response = await client.GetAsync(address);

            if (response.RequestMessage.RequestUri.Host.Contains("consent.youtube.com"))
            {
                using (HttpClient consentClient = new HttpClient())
                {
                    var consentResponse = await response.Content.ReadAsStringAsync();
                    HtmlDocument document = new HtmlDocument();
                    document.LoadHtml(consentResponse);

                    var forms = document.DocumentNode.SelectNodes("//form");
                    var form = forms.First(f => f.InnerHtml.Contains("hidden"));
                    var fields = form.SelectNodes("//input");

                    Dictionary<string, string> content = new Dictionary<string, string>();
                    foreach (var field in fields)
                    {
                        if (field.GetAttributeValue("type", "undefined") != "hidden") continue;
                        if (content.ContainsKey(field.GetAttributeValue("name", "undefined"))) continue;
                        content.Add(field.GetAttributeValue("name", "undefined"), field.GetAttributeValue("value", "undefined"));
                    }

                    IEnumerable<KeyValuePair<string, string>> entries = content.Select(entry => new KeyValuePair<string, string>(entry.Key, entry.Value));

                    FormUrlEncodedContent formularContent = new FormUrlEncodedContent(entries);
                    HttpResponseMessage constentResponse = await consentClient.PostAsync("https://consent.youtube.com/s", formularContent);
                    return await constentResponse.Content.ReadAsStringAsync();
                }

            }
            return await client.GetStringAsync(address);
        }

**Comment by omansak** [comment]
i edited pls try again @wolfSYS

**Comment by HiImLesic** [comment]
this works @omansak

**Comment by omansak** [comment]
please test 3.1.1 on github and nuget @HiImLesic  @akaelin  @wolfSYS

**Comment by omansak** [comment]
> this works @omansak

thx for your helping

**Comment by omansak** [comment]
@akaelin  great thanks for helping

**Comment by HiImLesic** [comment]
nuget works aswell, thank you very much!

**Comment by SMarconetto** [comment]
@omansak Yes NuGet 3.1.1 works! Thank you!

**Comment by wolfSYS** [comment]
Great work, thank you very much!
