### ISSUE TITLE
Possibility to Get Upload Date of Video

### ISSUE THREAD

**Issue by charlieahill** [omansak/libvideo#212]
Hello, is there a possibility to get the upload date of a YouTube video from the VideoInfo?

**Comment by sepp89117** [comment]
Hi, you can get it from variable playerResponseJson in YouTube.cs by adding:
```var uploadDate = playerResponseJson.SelectToken("microformat.playerMicroformatRenderer.uploadDate")?.Value<string>();```

**Comment by charlieahill** [comment]
Works perfectly! Thank you!

**Comment by omansak** [comment]
@charlieahill @sepp89117 u guys can add to VideoInfo object  and pull request via https://github.com/omansak/libvideo/blob/418db460756e51acbcb0d53c523f3c8a37bc7a16/src/libvideo/YouTube.cs#L81
