### ISSUE TITLE
GetBytes Not working, just hanging

### ISSUE THREAD

**Issue by PureDevelopers** [omansak/libvideo#219]
### Discussed in https://github.com/omansak/libvideo/discussions/218

<div type='discussions-op-text'>

<sup>Originally posted by **PureDevelopers** October 18, 2021</sup>
I just found this package, and attempted to use it by creating a new app in VS.
When debugging, the app just hangs on the GetBytes method.

Any idea why or how to fix?

the following simply doesn't work for me:

`var youTube = YouTube.Default; // starting point for YouTube actions
    var video = youTube.GetVideo(link); // gets a Video object with info about the video
    File.WriteAllBytes(@"C:\" + video.FullName, video.GetBytes());`</div>

**Comment by ghost** [comment]
here is the path I am using: https://www.youtube.com/watch?v=Pxw5WTxJ7To

**Comment by omansak** [comment]
can you share your exception ?

**Comment by ghost** [comment]
Hi,
I wasn’t getting any errors, GetBytes was simply never returning.
I have gotten to a point now, where this code is working, but it is really slow.
I tried the chunking solution, but I am unable to get it to return anything. It just seems to run forever.

I would be happy to share my solution or just some of the code if you are interested.
How is the chunking solution working for you?



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by omansak** [comment]
@PureDevelopers 

ofc, I would be happy if you share your solution.

**Comment by omansak** [comment]
#220

**Comment by ghost** [comment]
Jim Shaffer has shared a OneDrive file with you. To view it, click the link below.
<https://1drv.ms/u/s!AvHPKApmHh2S0Uc4m7pdShzTuTKD>
[https://r1.res.office365.com/owa/prem/images/dc-zip_20.png]<https://1drv.ms/u/s!AvHPKApmHh2S0Uc4m7pdShzTuTKD>
WebApplication1.zip<https://1drv.ms/u/s!AvHPKApmHh2S0Uc4m7pdShzTuTKD>

I am attaching my solution. It is MVC web app, so just review the home controller.
The first method works and returns a file, but the one that chunks the file never returns anything.

________________________________

**Comment by omansak** [comment]
check version 3.1.3-pre (include prerelease if does not show on nuget)

**Comment by ghost** [comment]
Once I checked the pre release check box, I was able to see a 3.1.3 version and a 3.1.4 version.
I installed 3.1.3, but then I got some dependency errors.
I added the following two packages:
Jint
Esprima

And then it ran, but no file was ever generated.

It executes the following line of code, and then it never returns:

var response = await _client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);

**Comment by omansak** [comment]
can you try again with 1.3.4 with new dependencies (NiL.JS)?
