### ISSUE TITLE
how can download video in .mp4 format?

### ISSUE THREAD

**Issue by Harikrishnav21** [omansak/libvideo#22]
I am able to download Youtube video in .WebM format.
But I need video to be downloaded in .MP4 format.
I am unable to find a way to specify the response format for GetVideo method.
I am using this in Xamarin.iOS,it only downloads in .WebM format,but I need in .Mp4 to ply video in iPhone.

**Comment by i3arnon** [comment]
`GetVideo` just selects the first. You need to use `GetAllVideosAsync` and filter the results according to your liking:

```
var allVideos = await YouTube.Default.GetAllVideosAsync("...");
var mp4Videos = allVideos.Where(_ => _.Format == VideoFormat.Mp4);
```

**Comment by jamesqo** [comment]
Thanks, @i3arnon.

Harikrishnav, does this work for you?

**Comment by Harikrishnav21** [comment]
I  am checking,let you know once it  worked for me.

**Comment by Harikrishnav21** [comment]
@i3arnon,

Thank for your suggestion.
it is working good for me,I am able to play video's in iPhone.

**Comment by jamesqo** [comment]
Awesome! :smile:

**Comment by NicodemusU** [comment]
Wait, how do you download the video once it's converted to Async?
            byte[] bytes = await mp4Videos.GetBytesAsync();
doesn't work.
