### ISSUE TITLE
await video.GetBytesAsync() large delay

### ISSUE THREAD

**Issue by Dls79** [omansak/libvideo#220]
Great package! However I'm currently using ver3.1.2 and I am noticing that it takes 3.5 minutes to download and convert to mp3 when it used to take 10-15 seconds on previous versions of this package. I'm using "await video.GetBytesAsync())" I haven't tried downloading a video since the delay is too long. 

Please let me know if you need any additional info. 

Thanks in advance.

**Comment by JOBBIN9422** [comment]
I have been running into this issue too. I think there is definitely some sort of throttling going on from youtube's side.

https://code.videolan.org/videolan/vlc/-/issues/26174#note_286445

**Comment by omansak** [comment]
check version 3.1.4-pre (include prerelease if does not show on nuget)
