### ISSUE TITLE
Error Download Video

### ISSUE THREAD

**Issue by arogerm** [omansak/libvideo#225]
Dear All
if you try to download this video https://www.youtube.com/watch?v=9scTqHVE3A0 you get this error
Additional text encountered after finished reading JSON content: ;. Path '', line 1, position 66854.

¿there are some way to avoid this error?

with this other videos happens different json error
https://www.youtube.com/watch?v=qgnGm6mLFVw
https://www.youtube.com/watch?v=wHbz5xWbsHI

I'm using 3.1.4 version

**Comment by omansak** [comment]
Thx for feedback.
I will check it.
