### ISSUE TITLE
"IEnumerable<YouTubeVideo>" does not contain a definition for "First"

### ISSUE THREAD

**Issue by Hyva-arch** [omansak/libvideo#228]
![image](https://user-images.githubusercontent.com/84142332/149624936-8e95d1e9-0398-446b-ad96-e3cd80015e50.png)

The error shows that "var videoInfos" does not contain a definition for "First".
https://github.com/omansak/libvideo/blob/master/docs/README.md#advanced

(.NET Framework 4.7.2)

**Comment by omansak** [comment]
can you add `using System.Linq`
