### ISSUE TITLE
String was not recognized as a valid DateTime after upgrading to 3.1.1

### ISSUE THREAD

**Issue by RogerSchmidlin** [omansak/libvideo#23]
Just upgraded from 3.0.5 to 3.1.1. Everything worked with 3.0.5 but now I get following exception when calling:
danceMovesList = await dbConn.QueryAsync<TblVideos> ("SELECT V.\* FROM Videos AS V ORDER BY V.DateAdded COLLATE nocase DESC");
-> String was not recognized as a valid DateTime

Following call works fine:
List<TblVideos> danceMovesList = await dbConn.QueryAsync<TblVideos> ("SELECT V.\* FROM Videos AS V JOIN Videos_Tags AS t0 ON V.Id = t0.VideoFId AND t0.TagFId = 8 ORDER BY V.DateAdded COLLATE nocase DESC");

The second call seems to read the date just fine. I haven't changed my database format and content at all. I work with Xamarin Forms on a mac.

Any ideas?

**Comment by jamesqo** [comment]
@RogerSchmidlin Sorry, but I think you have the wrong repository. We don't expose any of the APIs you've listed.
