### ISSUE TITLE
GetVideo().GetBytes() sometimes throws HttpRequestException

### ISSUE THREAD

**Issue by SilkyKitsune** [omansak/libvideo#230]
works fine most of the time but it's suddenly throwing the System.Net.Http.HttpRequestException. It throws this exception with videos it normally works fine with so I'm not sure what's going on. If there's more relevant information on the exception I can gather please tell me so.

**Comment by omansak** [comment]
ty for feedback, next time can you share full error or stack trace ?

**Comment by SilkyKitsune** [comment]
Yes I will do so as soon as I am able to

**Comment by SilkyKitsune** [comment]
Here you go, I managed to throw it a few times so I figured I'd just put all of their details in there
[HttpRequestException Details.txt](https://github.com/omansak/libvideo/files/8009179/HttpRequestException.Details.txt)

**Comment by omansak** [comment]
This issue is out of date.
