### ISSUE TITLE
Versions 3.1.4 and above not working on iOS

### ISSUE THREAD

**Issue by nikrath** [omansak/libvideo#232]
Hi,
I am trying to fix the slow GetBytes() problem by updating to 3.1.4 as mentioned in pinned issue. But unlike earlier versions, v3.1.4 is not working on iOS.
It throws the following error:
```
The type initializer for 'NiL.JS.Core.Context' threw an exception.
```

I think this might be happening because Nil.JS is a non-mobile only library.
Is there any solution / alternative to this library?

Thanks

**Comment by omansak** [comment]
i will check that

**Comment by omansak** [comment]
can you try 3.1.7?

**Comment by omansak** [comment]
NiL.JS might can not run on İOS , i can replace this Javascript Engine with another one that works on İOS . Do you know another JS Engine that works on IOS ? I am waiting jint release version

**Comment by nikrath** [comment]
Hey Omanask
Thanks for your response

> NiL.JS might can not run on İOS , i can replace this Javascript Engine with another one that works on İOS . Do you know another JS Engine that works on IOS ? I am waiting jint release version

Let me research a bit, try to find an alternative.
Also, what features / updates of Jint are you waiting for?

**Comment by ColorTwist** [comment]
I can confirm that even for android there are issues (not functional) because of NiL.JS library, if I'll find an alternative I'll update.

**Comment by ColorTwist** [comment]
@nikrath @omansak 
Hi,
Do you have any update from your side?

**Comment by ColorTwist** [comment]
From what i have read this version could support iOS/Android, not 100%, however, if possible to try it would be great:
https://github.com/sebastienros/jint

**Comment by omansak** [comment]
@ColorTwist  we are waiting none-beta version 3.x.x (2.x.x does not work i did tried.) but you can own build from beta3

**Comment by ColorTwist** [comment]
I can't test the build now :| Do you know when none-beta will be released?

**Comment by omansak** [comment]
https://github.com/sebastienros/jint/issues/343#issuecomment-1086982853 :)

**Comment by lahma** [comment]
Hi folks. You should definitely give Jint 3.x a try even though it's marked beta. Beta label allows changing some APIs and other wiggle room but the actual JS execution is backed by thousands of tests (> 30 000), and it should get better in every release. I'd argue that Jint handles the same set of features as other libraries, if even not more.

**Comment by omansak** [comment]
I changed JS Engine to Jurassic Engine. Can anyone test it ?

**Comment by lahma** [comment]
@omansak just curious, why the change? Jint too slow or iOS related?

**Comment by omansak** [comment]
jint does not support ES6+

**Comment by lahma** [comment]
Hmm, if you compare both projects readmes, you can see that Jint supports more of the recent features than Jurassic 🙂

Jint has things like rest, spread, destructuring, arrow functions, also the base library has more constructs implemented.

**Comment by omansak** [comment]
NilJs removed
