### ISSUE TITLE
How do you show download progress?

### ISSUE THREAD

**Issue by maaa3** [omansak/libvideo#238]
Im making a Windows Forms youtube downloader application with libvideo, and i was wondering how i show download progress (e.g. 50% downloaded)? Sorry if this isn't the right place to ask

**Comment by marnagy** [comment]
Hello @Ma0us , 

I personally download from stream using buffer and in while loop fill the buffer. In the loop, I keep track of amount of bytes read in total. Total amount of bytes to be downloaded is stored in `stream.ContentLength`.

I use this in CLI with progress bar, so you will need to modify the code, but I hope it will be a good starting place.
[Link to my project](https://github.com/marnagy/YTDownloader/blob/master/YTDownloader/Program.cs): method you need is  on line 369.

Hope this helps.

**Comment by omansak** [comment]
https://github.com/omansak/libvideo/blob/master/docs/README.md

on the bottom
