### ISSUE TITLE
Audio downoad

### ISSUE THREAD

**Issue by ghost** [omansak/libvideo#24]
Hi! I want to make an UWP app that downloads the audio from Youtube video and saves it to phone/PC. Since I have just discovered libvideo by browsing through the internet, I want to ask you if this "tool" allows me to download only audio from given Youtube video URL and saves it in device storage? If it can do that, can you please show me one code sample? To be honest, I want to know how would look the c# code behind the DOWNLOAD BUTTON in my app? Thank you!

**Comment by i3arnon** [comment]
@IgorGiga not exactly the same... but you may want to take a look at YouCast: http://youcast.i3arnon.com/

**Comment by jamesqo** [comment]
@IgorGiga Hi! Unfortunately, audio extraction is a work in progress at the moment, so it's not available yet. What you can try is downloading the code from [FLV Extract](http://moitah.net/) and tweaking it a bit to work on UWP. Once you've done that, you'll be able to extract the audio like so:

``` csharp
string ExtractAudioFromVideo(string url)
{
    var video = YouTube.Default.GetAllVideos(url).First(v => v.Format == VideoFormat.Flash);
    File.WriteAllBytes("somewhere.flv", video.GetBytes()); // or whatever you use in UWP
    // Use refactorted FLV Extract code to extract the video from somewhere.flv...
    return pathToAudio;
}
```

Good luck.

**Comment by ghost** [comment]
Thank you for an answer! I will try that... BTW, when you will finish the audio extraction for libvideo? Sometime soon or...?

**Comment by jamesqo** [comment]
Hmm... Probably within the next few weeks. I'm a bit busy right now though, so no promises.

**Comment by ghost** [comment]
Ok... I think I will be here, when you finish it... :) I will wait, because this is the best tool I have found till now... And because it supports UWP! Nice.
