### ISSUE TITLE
Could not install package 'VideoLibrary 3.2.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### ISSUE THREAD

**Issue by tjvxh** [omansak/libvideo#248]
Could not install package 'VideoLibrary 3.2.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Version 3.1.9 was compatible with .NET Framework 4.8, but 3.2.1 seems to be considered incompatible.

**Comment by omansak** [comment]
hmm ok, you can use now 3.1.9 untill i fix problem.

**Comment by omansak** [comment]
fixed version 3.2.2
