### ISSUE TITLE
Is VideoLibrary compatible with .NET MAUI?

### ISSUE THREAD

**Issue by tjvxh** [omansak/libvideo#261]
I see that it should be compatible with Xamarin, but would it also be compatible with .NET MAUI?
I was attempting to implement a video downloader, but I received this exception.

Exception thrown: 'VideoLibrary.Exceptions.UnavailableStreamException' in System.Private.CoreLib.dll

I'm unsure if it's an issue with my implementation (I'm still new to MAUI and Xamarin) or if the library isn't compatible.

**Comment by hondek** [comment]
Can you show some part of your code?

**Comment by hondek** [comment]
Or Message from throwed UnavailableStreamException.

**Comment by omansak** [comment]
please share us Exception.

**Comment by tjvxh** [comment]
Here's the exception, sorry for the delay

VideoLibrary.Exceptions.UnavailableStreamException: Video has unavailable stream.
at VideoLibrary.YouTube.ParseVideos(String source)+MoveNext() at System.Linq.Enumerable.TryGetFirst[TSource(IEnumerable`1 source, Boolean& found) at System.Linq.Enumerable.First[TSource](IEnumerable`1 source) at VideoLibrary.ServiceBase 1.GetVideoAsync(String videoUri, Func`2 sourceFactory) at SampleDownloader.DownloadAsVideo.DownloadVideo(String link, String saveTo)

Again, I'm not entirely sure if this is an issue with the library or with my code specifically. Here's what I'm using to download it, in my page DownloadAsVideo.xaml.cs


```
using (var service = Client.For(YouTube.Default))
			{
				var video = await service.GetVideoAsync(link);
			}
			if (saveTo.Length > 0)
			{
				ResultLink = Directory.GetParent(saveTo).ToString();
			}

```

**Comment by tjvxh** [comment]
I believe I have resolved the issue and it seems to work now

**Comment by rochapablo** [comment]
@tjvxh how did you resolve the issue?
