### ISSUE TITLE
Try to download the video with getallvideos, but got 503 error.

### ISSUE THREAD

**Issue by fema3832** [omansak/libvideo#268]
When i try to downlaod the best quality video with libvideo with a c# .net code:
```
 IEnumerable<YouTubeVideo> videos = youtube.GetAllVideos(Url);
 video = videos.OrderByDescending(o => o.Resolution).ThenByDescending(o => o.Fps).First();
 File.WriteAllBytes(videoPath, video.GetBytes());
```
I got an error: System.Net.Http.HttpRequestException: Response status code does indicate success: 503 (Service Unavaliable)
![uqmVXJGnt6](https://user-images.githubusercontent.com/88377040/208249301-1f8c2c27-3b97-4c76-97c5-36225fc37f00.png)

**Comment by mohammadjouhari** [comment]
is the issue resolved I am geting 503 in youtube.GetVideo(); any Reason ? No excpetion is being thrown ? why >?

**Comment by omansak** [comment]
#270
