### ISSUE TITLE
HttpRequestException: 'Response status code does not indicate success: 429 (Too Many Requests).'

### ISSUE THREAD

**Issue by AliiMohammadi** [omansak/libvideo#274]
I tried the valks project (that demo console application project) but I get 
System.Net.Http.HttpRequestException: 'Response status code does not indicate success: 429 (Too Many Requests).' 
error in 
var video = service.GetVideo("https://youtube.com/watch?v=" + id); line.
I use pvn.
How can I fix it? I use the lates vertion (3.2.3).

**Comment by omansak** [comment]
#270
