### ISSUE TITLE
Obtaining the URL for a specific video and resolution

### ISSUE THREAD

**Issue by RubenGarcia** [omansak/libvideo#276]
Can you add an example in the documentation about querying the specific URL which will be downloaded when using video.GetBytes()? 
This would allow users to pass this url to a Unity VideoPlayer component, which would then allow downloading-as-you-view.

**Comment by RubenGarcia** [comment]
video.Uri gives the default URL.

I could not find documentation about the second (optional) parameter Func<string, Task<string>> sourceFactory, which I guess is used to select the resolution and bitrate.

**Comment by omansak** [comment]
Can u see this https://github.com/omansak/libvideo/blob/master/docs/README.md ?

**Comment by RubenGarcia** [comment]
I can see the README file, but I still don't know how to get the uris of the different videos.
Can they be accessed inside videoInfos somewhere?

**Comment by omansak** [comment]
All
`var videoInfos = Client.For(YouTube.Default).GetAllVideosAsync(uri).GetAwaiter().GetResult();`

Specific
`var maxResolution = videoInfos.First(i => i.Resolution == videoInfos.Max(j => j.Resolution));`

PS:
https://github.com/omansak/libvideo/issues/198

**Comment by RubenGarcia** [comment]
Ah, so maxResolution is not the maximum resolution, but the information about the specific video, where the url can be accessed?
So maxResolution.Uri is what I want. I'll test it tomorrow.

**Comment by omansak** [comment]
i will close that @RubenGarcia , if you ok ?

**Comment by RubenGarcia** [comment]
I did not have time to test, but you can close and I'll reopen if I still have issues.

**Comment by RubenGarcia** [comment]
I confirm I can chose the desired resolution now. Next step: find the audio stream for videos with no audio.
