### ISSUE TITLE
IHttpClientFactory support

### ISSUE THREAD

**Issue by MaxLevs** [omansak/libvideo#278]
I really miss the feature to use the IHttpClientFactory to produce a HttpClient instance. It would be great to have this feature as well as DI support.

**Comment by omansak** [comment]
Can u try write your own custom client like as https://github.com/omansak/libvideo/blob/master/src/libvideo.debug/CustomYoutubeClient.cs

**Comment by techiedesu** [comment]
`IHttpClientFactory` requires .net standard 2.0 or higher, but current target is netstandard1.1. So, why not use `HttpClient`?
