### ISSUE TITLE
On the start i get an error.

### ISSUE THREAD

**Issue by Kostya-An** [omansak/libvideo#279]
System.IO.FileLoadException: "Could not load file or assembly 'libvideo, Version=3.2.3.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)"

Help please

**Comment by gordon-matt** [comment]
@Kostya-An How did you fix it? I'm getting the same thing now
UPDATE: Nevermind. It seems to disappear after rebuilding and running it the second time.
