### ISSUE TITLE
GetAllVideos not working

### ISSUE THREAD

**Issue by noammaoz508** [omansak/libvideo#284]
I have upgraded to the new version the GetAllVideos function is not working.
The following is my code:
 var url = "https://www.youtube.com/watch?v=Sf5XYmNlhpY";
        var youtube = YouTube.Default;
        var videos = youtube.GetAllVideos(url).ToList();
        var audios = videos.Where(video => video.AdaptiveKind == AdaptiveKind.Audio).OrderByDescending(video => video.AudioBitrate).ToList();
        var audio = audios.First();

        if (audio != null && audio.Format == VideoFormat.Mp4) {
            var bSong = audio.GetBytes();
            MessageBox.Show("Audio File");
        } else {
            var video = youtube.GetVideo(url);
            var bSong = video.GetBytes();
            MessageBox.Show("video File");
        }

Getting the video only is working fine:
var video = youtube.GetVideo(url);
var bSong = video.GetBytes();

Any idea why it's not working?

**Comment by omansak** [comment]
@noammaoz508 did u try this on last version ?

**Comment by notorious-bd** [comment]
The new version resolves the following error: 

System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=Response status code does not indicate success: 403 (Forbidden).

Thank You!

**Comment by noammaoz508** [comment]
Yes. I'm using the latest version 3.2.4

**Comment by noammaoz508** [comment]
Any idea how to solve this problem of the GetAllVideos?

**Comment by omansak** [comment]
@noammaoz508 i checked now but i did not find any issue. Your code perfectly on master branch

**Comment by omansak** [comment]
@noammaoz508 Can you test version 3.45
