### ISSUE TITLE
GetAllVideosAsync And GetVideoAsync Not Working

### ISSUE THREAD

**Issue by hady-khann** [omansak/libvideo#285]
Hi 
recently i cant get get any video 
i use code below :

`IEnumerable<YouTubeVideo> Qualities = await YouTube.Default.GetAllVideosAsync(URL);`

i get this error : Error = Unable to evaluate the expression. Operation not supported. Unknown error: 0x80070057.

And When Using :
`YouTubeVideo Quality = await YouTube.Default.GetVideoAsync(URL);`

i get this error : VideoLibrary.Exceptions.UnavailableStreamException

And SomeTimes This Error : cannot evaluate expression since the function evaluation requires all threads to run.

**Comment by omansak** [comment]
@hady-khann Hello thank you for issue and pull request.  `GetPlayerResponseAndroidAsync` moved into `GetAllVideosAsync`. 
Now async funcs work perfectly. Can you test it ?

**Comment by hady-khann** [comment]
> @hady-khann Hello thank you for issue and pull request. `GetPlayerResponseAndroidAsync` moved into `GetAllVideosAsync`. Now async funcs work perfectly. Can you test it ?

@omansak  hi , thanks to reply and fix bug . now it works perfectly in my tests .
