### ISSUE TITLE
Getting feedback regarding download

### ISSUE THREAD

**Issue by andreaciarrocchi** [omansak/libvideo#29]
Dear developers,
thank you for providing this great library. I think it would be useful to get some feedback during the download (bytes received / bytes total). Otherwise, users can easily think the app has frozen.
Nice work.

Andrea Ciarrocchi

**Comment by Black-Platypus** [comment]
Seconded.
(meanwhile, you can use the asynchronous downloads and display something like a spinner to indicate a running background task)
