### ISSUE TITLE
Flie is not working

### ISSUE THREAD

**Issue by noammaoz** [omansak/libvideo#292]
Something is wrong with GetBytes function.

I have tried the following code and it saved the file but the file can't be played:

```
var url = "https://www.youtube.com/watch?v=Sf5XYmNlhpY";
        var youtube = YouTube.Default;
        var videos = youtube.GetAllVideos(url).ToList();
        var videosMP4 = videos.Where(video => video.AdaptiveKind == AdaptiveKind.Video && video.Format == VideoFormat.Mp4).OrderByDescending(video => video.Resolution).ToList();
         var video = videosMP4.First();
        File.WriteAllBytes(video.FullName, video.GetBytes());
```

Any idea?

**Comment by olilittle** [comment]
Seeing a similar issue here after updating the libraries earlier. Videos are downloading successfully, but the bitrate of the audio on the video is -1 causing Media Player to fail to load the file. VLC can handle playing the video back, but obviously there's no sound playback.

**Comment by pillo89** [comment]
Got the same issue: video created but without audio.

**Comment by noammaoz** [comment]
Any idea how to fix this issue or to use another library?

**Comment by olilittle** [comment]
I haven't had time recently, but if this doesn't get resolved sometime soon I may end up forking and applying the fix myself. I'll update if I do.

Also, it may be worth updating the title to something more descriptive of the issue :)

**Comment by rodrigojuarez** [comment]
Can anyone recommend any other .net library in the meantime?

**Comment by miyaji255** [comment]
YoutubeExplode may be what you wanted.

https://github.com/Tyrrrz/YoutubeExplode

**Comment by LordCM** [comment]
Streams with higher resolution don't have audio inside them. You have to download video, when audio as two separate streams/files, then mux them (using ffmpeg).

```
var allStreams = youtube.GetAllVideosAsync(url).GetAwaiter().GetResult();
var maxResolution = allStreams.OrderByDescending(i => i.Resolution).ThenBy(i=>VideoFormatSortOrder(i.Format)).ThenByDescending(i => i.Fps).First();
var maxAudio = allStreams.OrderBy(i => (int)i.AudioFormat).ThenByDescending(i => i.AudioBitrate).First();

youtube.CreateDownloadAsync(new Uri(maxResolution.Uri), "video.stream")
youtube.CreateDownloadAsync(new Uri(maxAudio.Uri), "audio.stream")

>> ffmpeg -i video.stream -i audio.stream out.mp4
```

**Comment by pillo89** [comment]
Thanks @LordCM! Your solution works! :)

**Comment by olilittle** [comment]
Thanks for the response LordCM ❤️ 

Any idea what or where something changed? I (and I expect others) have been using this functionality in the same way for months/years now without seeing this issue at all 😂

**Comment by omansak** [comment]
https://github.com/omansak/libvideo/issues/288#issuecomment-2385581045
