### ISSUE TITLE
Downloaded video has no audio stream in V3.2.6

### ISSUE THREAD

**Issue by doesch** [omansak/libvideo#295]
I use the following C#-code to download a video:

```
var url = "https://www.youtube.com/watch?v=ZwP8dfAVZp8";
var downloadFolder = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
var youtube = YouTube.Default;
var vid = youtube.GetVideo(url);
var path = Path.Combine(downloadFolder, vid.FullName);

System.IO.File.WriteAllBytes(path, vid.GetBytes());
```

Unfortunately, the downloaded mp4-File has no sound, because the audio stream is missing. You can check the audio stream via [ffmpge.exe](https://www.ffmpeg.org/download.html#build-windows):

`fmpeg.exe -i filename.mp4`

Expected: the information output shows two streams:

```
Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 25k tbn, 50 tbc
Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
```

Current behavior: The audio stream is missing.

**Comment by olilittle** [comment]
Similar discussion to this thread, but this issue is much better worded :D 

https://github.com/omansak/libvideo/issues/292

**Comment by omansak** [comment]
https://github.com/omansak/libvideo/issues/288#issuecomment-2385581045
