### ISSUE TITLE
how can I determine if download link is video or audio only?

### ISSUE THREAD

**Issue by barterajay** [omansak/libvideo#30]

**Comment by Black-Platypus** [comment]
the `YouTubeVideo` class (what `.GetAllVideosAsync` returns, for example) has a property called `.AdaptiveKind`: an enumerator for `.Video,`, `.Audio` and `.None`

**Comment by Black-Platypus** [comment]
Also, in the link, there's a `mime` parameter. In your case, it's "Video/mp4"

**Comment by ajay-verma8245** [comment]
Thank you..
