### ISSUE TITLE
video quality

### ISSUE THREAD

**Issue by Mnjongen** [omansak/libvideo#31]
is there a way to only get for example the 480p video instead of the 1080p video?

**Comment by jamesqo** [comment]
Try filtering them by resolution:

``` cs
var videos = YouTube.Default.GetAllVideos("YOUR_URL");
var @480p = videos.FirstOrDefault(v => v.Resolution == 480);
```

**Comment by eslam-zafer** [comment]
I have downloaded a video in 480p resolution then download is very very slow and no audio in video, please any solution please.
