### ISSUE TITLE
"VideoLibrary.Exceptions.BadQueryException"

### ISSUE THREAD

**Issue by ATypescriptEnjoyer** [omansak/libvideo#33]
What does this error actually mean? The song I tried with it used to work, but now no longer works, and i'm really unsure why :(

Any help would be awesome

Cheers.

**Comment by ATypescriptEnjoyer** [comment]
Update: Managed to fix by trying over and over to get the info for the URL. Takes about 5-10 attempts to get it working

**Comment by iancona** [comment]
Same issue here..

**Comment by ATypescriptEnjoyer** [comment]
I think it's a problem with a youtube update, it CAN retrieve the video it just takes a few attempts. Check out my TS3MusicBot to see how I did it if need be :P

**Comment by gwigz** [comment]
This section of the URI that is fetched is throwing it off, as there's two sets of equals in the query string; `axtags=tx=9417362`.

**Comment by gwigz** [comment]
Removing [this conditional](https://github.com/jamesqo/libvideo/commit/7dadee84108505fd6e8413b160d9fc1920c8e6e0#diff-b2a80c84d438bca2c7fad9979432d69cR51) would fix this issue, not sure if there'd be any fallout due to the removal of that check though, doubt it.

**Comment by gwigz** [comment]
Removing [this conditional](https://github.com/jamesqo/libvideo/commit/842115804a1b19ba59e2b74616114e1b4bc5e78c) causes the following exception:

``` txt
An unhandled exception of type 'YoutubeExtractor.YoutubeParseException' occurred in YoutubeExtractor.dll

Additional information: Could not parse the Youtube page for URL http://youtube.com/watch?v=IB3lcPjvWLA

This may be due to a change of the Youtube page structure.

Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues
```

**Comment by namlai000** [comment]
how about chang to API youtube-dl ... it's totally works flawless

**Comment by gwigz** [comment]
https://github.com/flagbug/YoutubeExtractor/issues/179
