### ISSUE TITLE
Audio stream

### ISSUE THREAD

**Issue by Beallitasok** [omansak/libvideo#38]
Hello, since Im making something like youtube music player for private usage, can libvideo stream only music, without video? It's the best YouTube .net library :)

**Comment by Grimitsu** [comment]
You'll have to use something else. I would recommend you to use NAudio to make a player and FFmpeg for converting videos to audio files. YouTube stores only videos.

**Comment by i3arnon** [comment]
Relevant: https://github.com/jamesqo/libvideo/issues/6#issuecomment-162839944
