### ISSUE TITLE
Corrupt ID3 Tags

### ISSUE THREAD

**Issue by PikaDude** [omansak/libvideo#40]
Hi, I've been using LibVideo for quite a while now, however, lately I've been experiencing issues with downloading the audio track from a video. When I download it, the ID3 tag seems to be corrupt. Is there any way to fix this?

**Comment by jamesqo** [comment]
@PikaDude Did you just update to a new version? What video are you having issues with? I'm slightly busy at the moment, but if I get around it I may be able to look into your issue.

**Comment by PikaDude** [comment]
I managed to fix it. It had nothing to do with LibVideo. Another package called NAudio was having problems opening it so I switched to ffmpeg and now it works
