### ISSUE TITLE
Can I get other resolution video?

### ISSUE THREAD

**Issue by knight7024** [omansak/libvideo#41]
I'm making Youtube Player but 

```
        var youTube = YouTube.Default;
        var video = youTube.GetVideo(link);
```

this is just able to get low resolution. How I get various resolution video link?

**Comment by Pyroglyph** [comment]
Quoted from the docs:
YouTube exposes multiple videos for each URL- e.g. when you change the resolution of a video, you're actually watching a different video. libvideo supports downloading multiple of them:

var videos = youTube.GetAllVideos(uri);

**Comment by ghost** [comment]
how to know what is the better res. video and only download this?
thanks

**Comment by Pyroglyph** [comment]
GetAllVideos() returns an IEnumerable containing multiple YoutubeVideo objects of various qualities. Simply iterate through them and select the highest resolution. The resolution is stored in an int called Resolution in the YoutubeVideo object.

**Comment by ghost** [comment]
ok
thanks
can you please give some example in vb.net?

**Comment by acosano** [comment]
Just have a look at this post [https://github.com/jamesqo/libvideo/issues/49](https://github.com/jamesqo/libvideo/issues/49), I just answer your question with sample code.
