### ISSUE TITLE
YouTube playlist support?

### ISSUE THREAD

**Issue by Pyroglyph** [omansak/libvideo#42]
I was thinking, maybe some functionality could be added which supports playlists? Like perhaps a video.GetNextVideo() which returns the video which YouTube Autoplay would have played next, and also support for inputting a playlist URL and returning an array/list of YoutubeVideos? Features like this would be invaluable to my project and I'm certain it will be much appreciated by others as well.

**Comment by ATypescriptEnjoyer** [comment]
Check my github for a sort of implementation. Its called YoutubePLAYLIST something or other.

**Comment by Tyrrrz** [comment]
[YoutubeExplode](https://github.com/Tyrrrz/YoutubeExplode) supports getting video ids from playlists
