### ISSUE TITLE
How to get progress value?

### ISSUE THREAD

**Issue by ahensialevich** [omansak/libvideo#47]
How can I get some progress information about downloading process? For example, Youtube Extractor uses VideoDownloader, which can be attached to event handler (DownloadProgressChanged).

**Comment by akcorp2003** [comment]
That would be a nice feature to get! I think currently, the code is doing a functional approach so getting a progress value might not be possible. I can't be certain though.

**Comment by cYnd** [comment]
I appreciate a progress information too.

**Comment by nefarius** [comment]
This was bothering me too, [I fixed it in my fork](https://github.com/nefarius/libvideo) ([My NuGet](https://www.nuget.org/packages/Nefarius-VideoLibrary/)). Access the Stream length like this:

```C#
using (var service = Client.For(YouTube.Default))
{
	using (var video = service.GetVideo(url.AbsoluteUri))
	{
		// Stream size
		var streamLength = (long) video.StreamLength();
	}
}
```

**Comment by nefarius** [comment]
To get progress while downloading I use it in conjunction with [ProgressStream](http://mel-green.com/2010/01/progressstream/):

```C#
using (var service = Client.For(YouTube.Default))
{
	using (var video = service.GetVideo(videoUrl))
	{
		using (var outFile = File.OpenWrite("video.mp4"))
		{
			using (var ps = new ProgressStream(outFile))
			{
				var streamLength = (long) video.StreamLength();

				ps.BytesMoved += (sender, args) =>
				{
					var percentage = args.StreamLength * 100 / streamLength;
					Console.WriteLine($"{percentage}% of video downloaded");
				};

				video.Stream().CopyTo(ps);
			}
		}
	}
}
```

**Comment by akcorp2003** [comment]
Will this become a pull request?

**Comment by nickbrick** [comment]
> To get progress while downloading I use it in conjunction with [ProgressStream](http://mel-green.com/2010/01/progressstream/):
> 
> ```cs
> ps.BytesMoved += (sender, args) =>
> {
> 		var percentage = args.StreamLength * 100 / streamLength;
> 		Console.WriteLine($"{percentage}% of video downloaded");
> };
> ```
Thanks for this code. Correction for future readers, it should be ```args.StreamPosition * 100 / streamLength;```
