### ISSUE TITLE
Getting the video ID?

### ISSUE THREAD

**Issue by akcorp2003** [omansak/libvideo#48]
It would be a nice feature if we could get the video IDs. I was wondering if that would be possible to add?

**Comment by Tyrrrz** [comment]
[YoutubeExplode](https://github.com/Tyrrrz/YoutubeExplode) has that

**Comment by MJWherry** [comment]
Use a regex expression
This is mine:
youtu(?:\.be|be\.com)/(?:.*v(?:/|=)|(?:.*/)?)([a-zA-Z0-9-_]+)
it gets an id from all youtube link formats

**Comment by narqs** [comment]
Using YouTube's api, you could seach on YouTube and get the desired video id, and a bunch of other things like thumbnails and playlists
**Google.Apis.YouTube.v3;**
it's quite simple to use
https://developers.google.com/youtube/v3/code_samples/dotnet

**Comment by omansak** [comment]
Fixed. Update 3.0.0
