### ISSUE TITLE
Change download resolution with Visual Basic

### ISSUE THREAD

**Issue by ipmanlk** [omansak/libvideo#49]
Hi, how to change the resolution of downloading video in Visual Basic? (360p,480p etc.).  

`Dim video = YouTube.Default.GetAllVideos("https://www.youtube.com/watch?v=id")` can get all video resolutions, but how can I select the resolution I want to download?

**Comment by ghost** [comment]
I need help too.

**Comment by acosano** [comment]
Here we go, I hope this will help get you starting. I assume you using a Combobox to show the available Video formats and the Combobox don't support the item Tag. Meaning either you display the Title or the Video Quality. So I have create a class CBOHelper with 2 properties that will do what you need. 
` 
Public Class CBOHelper

    Private VideoDescription As String
    Private VideoURl As String

    Public Sub New(ByVal VideoTitle As String, ByVal VideoLink As String)

        Description =  VideoTitle
        Link = VideoLink

    End Sub

    Public Property Description() As String
        Get
            Return VideoDescription
        End Get
        Set(ByVal value As String)
            VideoDescription = value
        End Set
    End Property
    
        Get
            Return VideoURl
        End Get
        Set(ByVal value As String)
            VideoURl = value
        End Set
    End Property
    
End Class

`
And here the code to retrieve and bind the Combobox.

`
        Dim video = YouTube.Default.GetAllVideos(uri)

        Try

            Dim desc As New List(Of CBOHelper)

            For Each Vid In video.ToArray

                desc.Add(New CBOHelper(String.Format("{0} - {1}",Vid.FullName.Replace(" - YouTube", String.Empty), Vid.Resolution), Vid.GetUri))
                            
            Next

            cboVideos.DataSource = desc
            cboVideos.DisplayMember = "Description"
            cboVideos.ValueMember = "Link"

        Catch ex As Exception

            ' Handle your error here

        End Try

`

When you select a Title from the Combobox  just get the SelectedValue.

`
    Private Sub cboVideos_SelectedIndexChanged(sender As Object, e As EventArgs) Handles cboVideos.SelectedIndexChanged

       Dim DownloadUrl As String = cboVideos.SelectedValue  

    End Sub
`

Let me know if this help you or if you need some clarifications.
