### ISSUE TITLE
Cannot access the video stream

### ISSUE THREAD

**Issue by DavidBarishev** [omansak/libvideo#50]
Hello !
I must say that i absolutely love this repository, but i have found a really annoying bug that limiting me on my project.
I'm trying to access the stream in order to copy it to stdin of child process, here is the code:

```
var youTube = YouTube.Default; // starting point for YouTube actions
var video = await youTube.GetVideoAsync("https://www.youtube.com/watch?v=UjstuQx9Ixc"); // gets a Video object with info about the video

using (var stream = await video.StreamAsync())
{
     await stream.CopyToAsync(process.StandardInput.BaseStream);
}
```

I'm getting an disposed object error, here is the full exception:
```
Unhandled Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
```

Anyone has an idea why is this happening ?

**Comment by aseber** [comment]
I'm trying to do the exact same thing in my program and I've come to the same problem. If there is anyone who better understands the API that could help us, it would be greatly appreciated!

**Comment by nefarius** [comment]
This was bothering me too, it's a pretty severe bug, [I fixed it in my fork](https://github.com/nefarius/libvideo) ([My NuGet](https://www.nuget.org/packages/Nefarius-VideoLibrary/)). Access the Stream like this:

```C#
using (var service = Client.For(YouTube.Default))
{
	using (var video = service.GetVideo(url.AbsoluteUri))
	{
		using (var outFile = File.OpenWrite(tmpSource))
		{
			// Stream size
			var streamLength = (long) video.StreamLength();
			var stream = video.Stream();

			stream.CopyTo(outFile);
		}
	}
}
```

**Comment by nefarius** [comment]
To get progress while downloading I use it in conjunction with [ProgressStream](http://mel-green.com/2010/01/progressstream/):

```
using (var service = Client.For(YouTube.Default))
{
	using (var video = service.GetVideo(videoUrl))
	{
		using (var outFile = File.OpenWrite("video.mp4"))
		{
			using (var ps = new ProgressStream(outFile))
			{
				var streamLength = (long) video.StreamLength();

				ps.BytesMoved += (sender, args) =>
				{
					var percentage = args.StreamLength * 100 / streamLength;
					Console.WriteLine($"{percentage}% of video downloaded");
				};

				video.Stream().CopyTo(ps);
			}
		}
	}
}
```

**Comment by DavidBarishev** [comment]
I have actually moved to YouTube explode by trazz library , it's really great and works perfectly.

**Comment by nefarius** [comment]
@DavidBarishev link?

**Comment by DavidBarishev** [comment]
https://github.com/Tyrrrz/YoutubeExplode

**Comment by nefarius** [comment]
Thank you.

**Comment by aseber** [comment]
Thank you for the link to the other library. I'll use that for the time being as well!
