### ISSUE TITLE
.NET Core compatibility

### ISSUE THREAD

**Issue by AdrienTorris** [omansak/libvideo#51]
It would be great to can use this library in .NET Core projects.

When we reference the nuget package in a .NET Core project, we have the following error : 
_NU1002	The dependency VideoLibrary 1.3.4 does not support framework .NETCoreApp,Version=v1.0._

**Comment by AdrienTorris** [comment]
https://github.com/jamesqo/libvideo/pull/52

**Comment by Grimitsu** [comment]
use `portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10` moniker in your project to import packages or `portable-net45+win+wpa81` or `portable-net45+win8+wpa81`.
