### ISSUE TITLE
vb.net and end of download

### ISSUE THREAD

**Issue by ghost** [omansak/libvideo#55]
hello
how to know, using vb.net when the video download process is finished?
when i download a video, and i see the size is the right, i can not open it until some time has passed... but i do not know how many time...
any help?
thanks

**Comment by hakiour** [comment]
Hello,
If you do:
`YouTube.Default.GetVideo(link)`
`File.WriteAllBytes("C:\" & video.FullName, video.GetBytes())`
`MessageBox.Show("Hello world!")`
When alert "Hello world" is displayed, it means you video is downloaded on C:\, and ready to play it.

**Comment by kiquenet** [comment]
Can You create unit tests in project , c#? Then convert to VB easy

**Comment by omansak** [comment]
Fixed. Update 3.0.0
