### ISSUE TITLE
System.ArgumentOutOfRangeException when getting encrypted video url

### ISSUE THREAD

**Issue by Sracinas** [omansak/libvideo#58]
This is what I get when trying to get uri of the video.
'new System.Linq.SystemCore_EnumerableDebugView<VideoLibrary.YouTubeVideo>(videos).Items[0].Uri' threw an exception of type 'System.ArgumentOutOfRangeException'

I look for videos like this:
IEnumerable<YouTubeVideo> videos = YouTube.Default.GetAllVideos(url)
                .Where(x => x.Format != VideoFormat.Unknown && x.Format != VideoFormat.Flash && x.AudioFormat != AudioFormat.Unknown).OrderByDescending(x => x.Resolution);

It gets urls of some videos and some it doesn't. Does it have something to do with encryption of videos?

It worked on 05-01-2017 and earlier, but next day it suddenly stopped.

EDIT: I checked and it cannot get encypted videos url.
2nd EDIT: If it helps. It works with YoutubeExtractor.

**Comment by ATypescriptEnjoyer** [comment]
Hey, so do encrypted videos work with youtube extractor?

**Comment by omansak** [comment]
Fixed. Update 3.0.0
