### ISSUE TITLE
[POLL] Support Flash audio extraction

### ISSUE THREAD

**Issue by jamesqo** [omansak/libvideo#6]
Right now I haven't implemented audio extraction for maintainability && SRP reasons. If you're interested leave a comment here and I'll port it if enough people respond.

**Comment by Qandil** [comment]
That would be a great @jamesqo

**Comment by aloisdg** [comment]
Could be a nice option. Keep it lightweight though.

**Comment by Qandil** [comment]
To make this feature perfect yet i guess #8 need to be resolved.

Right now it only works with flv links having sig or signature.

**Comment by i3arnon** [comment]
I wouldn't invest too much time in this.
You can easily get just the audio by using one of the DASH types where the audio and video are already separated.

**Comment by Qandil** [comment]
Maybe @jamesqo can add it in the next release.

```
protected byte[] ExtractAudio(Stream stream)
{
    var reader = new BinaryReader(stream);

    // Is stream a Flash Video stream
    if (reader.ReadChar() != 'F' || reader.ReadChar() != 'L' || reader.ReadChar() != 'V')
        throw new IOException("The file is not a FLV file.");

    // Is audio stream exists in the video stream
    var version = reader.ReadByte();
    var exists = reader.ReadByte();

    if ((exists != 5) && (exists != 4))
        throw new IOException("No Audio Stream");

    reader.ReadInt32(); // data offset of header. ignoring

    var output = new List<byte>();

    while (true)
    {
        try
        {
            reader.ReadInt32(); // PreviousTagSize0 skipping

            var tagType = reader.ReadByte();

            while (tagType != 8)
            {
                var skip = ReadNext3Bytes(reader) + 11;
                reader.BaseStream.Position += skip;

                tagType = reader.ReadByte();
            }

            var DataSize = ReadNext3Bytes(reader);

            reader.ReadInt32(); //skip timestamps 
            ReadNext3Bytes(reader); // skip streamID
            reader.ReadByte(); // skip audio header

            for (int i = 0; i < DataSize - 1; i++)
                output.Add(reader.ReadByte());
        }
        catch
        {
            break;
        }
    }

    return output.ToArray();
}

private long ReadNext3Bytes(BinaryReader reader)
{
    try
    {
        return Math.Abs((reader.ReadByte() & 0xFF) * 256 * 256 + (reader.ReadByte() & 0xFF)
            * 256 + (reader.ReadByte() & 0xFF));
    }
    catch
    {
        return 0;
    }
}
```

Source: (Extract Audio from FLV stream in C#)[http://stackoverflow.com/questions/1693656/extract-audio-from-flv-stream-in-c-sharp#answer-1694235]

**Comment by jamesqo** [comment]
Alright, alright. I was planning to keep it a surprise, but I'm working on an upcoming library that will add support for this. Here is a snippet of its code: https://gist.github.com/jamesqo/6784f734025e083cb011

**Comment by Qandil** [comment]
@jamesqo looks great! What about working with mp4 files?

**Comment by ghost** [comment]
Is the support working ? I'd like to, like YoutubeExtractor does, get the audio stream from a youtube URL. Anyway, this is a really great project!

**Comment by jamesqo** [comment]
@bbougot I've got most of the code down, but it's pretty hard to debug so it may take another week or so. I'll keep you tuned :wink: Glad you found this project useful!

**Comment by ghost** [comment]
@jamesqo  Perfect! Thank you so much, this is awesome!

**Comment by ghost** [comment]
Would be mind-blowing!

**Comment by i3arnon** [comment]
I feel that you guys are missing the fact that you can already get just the audio straight out of YouTube using one of the DASH types.
I don't see any need in parsing *.flv files to do that.
I've already implemented that in [YouCast](https://github.com/i3arnon/YouCast) if you're looking for an example: 
https://github.com/i3arnon/YouCast/blob/master/Source/Service/YoutubeFeed.cs#L153

**Comment by narqs** [comment]
@i3arnon  Hey how would i implement something like that into my current application? so that I can download the audio?

**Comment by i3arnon** [comment]
@narqs You need to call `GetAllVideos(Async)` and filter the results looking for DASH audio.
You can look at how I implemented it in the link above.

**Comment by narqs** [comment]
Oh that sure helped Thanks mate, I realized that I did not take a good look at your code, it's working now thanks again :)  :+1:

**Comment by jamesqo** [comment]
@i3arnon Thanks for helping out; I hadn't realized that was possible myself. In the meantime I've already started a [new project](https://github.com/jamesqo/flavor.net) (had to tear down the old one because of maintainability reasons), so it's too late I guess haha.

**Comment by jamesqo** [comment]
BTW, it looks like the YoutubeExtractor author has ported FlvExtract to PCLs: https://github.com/flagbug/FlvExtract
