### ISSUE TITLE
VideoLibrary stop working well

### ISSUE THREAD

**Issue by hakiour** [omansak/libvideo#60]
I think something is wrong, all my apps that use VideoLibrary for download videos stop working unexpectedly when someone try to download any video... This is the error:

> Se proporcionó un URI de solicitud no válido. El URI de solicitud debe ser un URI absoluto o debe establecerse BaseAddress.
**Translation**:
> An invalid request URI was provided. The request URI must be an absolute URI or BaseAddress must be set.

Any idea?

**Comment by cYnd** [comment]
Same error for me!
I'm using the VideoLibrary in VB.NET

**Comment by hakiour** [comment]
Same thing on YoutubeExtractor, I think Youtube change something

**Comment by hig-dev** [comment]
Fixed it in my fork https://github.com/hig-ag/libvideo and added a pull request #61

**Comment by TheLordAndrew** [comment]
Getting this error on the version I have from Nuget in Visual Studio 2015 with C#. Should I download your fork and compile it @hig-dev?

**Comment by aboe026** [comment]
I'm getting the same error, glad to hear its not just me. Would be great to get pr #61 merged in and updated in NuGet for Visual Studio.

**Comment by hig-dev** [comment]
@TheLordAndrew You should if you don't want to wait for @jamesqo.

**Comment by TheLordAndrew** [comment]
@hig-dev when do you think it'll be merged/jamesqo will write his own fix?

**Comment by hig-dev** [comment]
@TheLordAndrew I don't know. The latest commit was on 23 Jun 2016, so maybe never. I will update my fork because I'm using it in a production app (REAL Shuffle Player)

**Comment by TheLordAndrew** [comment]
Yeah, that was my fear. Anyway, we'll see I suppose.

**Comment by hig-dev** [comment]
Fixed YouTube Decryption again

**Comment by omansak** [comment]
Fixed. Update 3.0.0
