### ISSUE TITLE
How to get mp3 audio download url from a video?

### ISSUE THREAD

**Issue by aalitor** [omansak/libvideo#62]
I can't find any resource to extract mp3 url from a youtube video for libvideo. What is the code to do this?

Using this method I can't get any mp3 file.

```
YouTube yt = YouTube.Default;
string link = "https://www.youtube.com/watch?v=QNJL6nfu__Q";
foreach (var item in yt.GetAllVideos(link))
 {
    if (item.AdaptiveKind == AdaptiveKind.Audio)
    {
         Console.WriteLine(item.AudioFormat); 
    }
}
```

**Comment by acosano** [comment]
Your sample work for me. I get this 

> Michael  Jackson - They Don’t Care About Us (Brazil Version) (Official Video)

**Comment by aalitor** [comment]
I know the library success at getting the title of the video. I am talking about the 'Video.Uri' throws exception. So you must test it using 'item.Uri'

**Comment by narqs** [comment]
hey, i don't think you can exstract the mp3. you can however extract the audio only, and then convert it later on, this is how you extract the audio ->
`var audio = await YouTube.Default.GetAllVideosAsync(string.Format("URL"));`
` var audios = audio.Where(_ => _.AudioFormat == AudioFormat.Aac && _.AdaptiveKind == AdaptiveKind.Audio).ToList();`
` var mpAudio = audios.FirstOrDefault(x => x.AudioBitrate > 0);`

Then you would say

`var bytes = await mpAudio.GetBytesAsync();`

this is from an old project of mine it should work though

**Comment by narqs** [comment]
I haven't played around much with audio's but i think you can use the MediaToolkit from nuget
once importet you could do something like this.

**Example:** _The file you download would be saved to the desktop with this_
`string finalName;`
`string path;`

`final = video.FullName;`
`string save = System.IO.Path.Combine(path, finalName);
Convert();`

**finalName** _would be the fullname of your video, with the extension like_ **akon.aac** or **akon.mp4**

then use this


```
private void Convert()
        {
            string save = System.IO.Path.Combine(path, finalName);
            
            var inputFile = new MediaFile { Filename = save };
            var outputFile = new MediaFile { Filename = save + ".mp3" };
            using (var engine = new Engine())
            {
                engine.Convert(inputFile, outputFile);
            }
            if (File.Exists(save))
            {
                File.Delete(save);
            }
        }

```
not quite sure if this is they way to go, though, as i'm not sure if it's a legit mp3, it does work however, and i haven't had any problems with it yet.

**Comment by acosano** [comment]
Hi, Is working 100% for me. Let me know if you need the code, I'm using the code from [#67](https://github.com/jamesqo/libvideo/issues/67) with the MediaToolkit to convert to mp3 as describe above by narqs. BTW Thanks for the conversion code.

**Comment by omansak** [comment]
Fixed. Update 3.0.0
