### ISSUE TITLE
Downloading Videos

### ISSUE THREAD

**Issue by DusterTheFirst** [omansak/libvideo#63]
When using `vid.GetBytes()` On `https://www.youtube.com/watch?v=q6EoRBvdVPQ`, I get  An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.

The URL Has A base Adress But Keeps Throwing The Error.

**Comment by hig-dev** [comment]
See at issue #60. And the PR #61 should fix this issue.

**Comment by DusterTheFirst** [comment]
Thank You, I compiled your fork, i hope it gets accepted soon.

**Comment by omansak** [comment]
thx
