### ISSUE TITLE
How to get Video size

### ISSUE THREAD

**Issue by acosano** [omansak/libvideo#64]
Hi,
Is there anyway you can get the video size before downloading the video. I'm adding videos to a Queue with the title and the size and format. I know I can call the video download and get the size but thats a pain int he bud as you will make several calls depending on how many videos you queuing. Would there be a change to add that to the library??

Thanks for any help.

**Comment by Tyrrrz** [comment]
[YoutubeExplode](https://github.com/Tyrrrz/YoutubeExplode) does that automatically

**Comment by acosano** [comment]
Thanks for the info; I worked out from your code. Here sample.

` 
Public Shared Function GetFileSize(url As String) As String

        ' Initialize WebClient to make the call to the server
        Using obj As New WebClient()

            ' Initialize a Stream object to read the response from the server
            Using s As Stream = obj.OpenRead(url)

                ' Declare String Array to hold the conversion extension
                Dim Units As String() = {" B", " KB", " MB", " GB", " TB", " PB", " EB", " ZB", " YB"}
                ' Declare Variable to hold the Size
                Dim Size As Double = Long.Parse(obj.ResponseHeaders("Content-Length").ToString())
                ' Declare Integer Variable to get the conversion extension from the String Array
                Dim unit As Integer = 0

                ' Loop trough Size as long it is greater or equal of 1024
                While size >= 1024

                    ' Divide it by 1024
                    Size /= 1024

                    ' Increment the count to get the conversion extension from the String Array
                    Threading.Interlocked.Increment(unit)

                End While

                ' Return the Size formated with the conversion extension
                Return Size.ToString("N2") & Units(unit) ' NOTES "N2" = 2 Decimals, "N1" = 1 Decimal, "N0" = No Decimal

                ' Dispose the Stream Object
            End Using

            ' Dispose the Webclient 
        End Using

    End Function ' GetFileSize`

you can call this function like this: `Dim FileSize As String = GetFileSize("DECRYPTED VIDEO URL GOES HERE")`

**Comment by TrynCatchMeh** [comment]
I would love to know how to do this as well.

**Comment by omansak** [comment]
Fixed. Update 3.0.0
