### ISSUE TITLE
YouTubeVideo.Uri Exception

### ISSUE THREAD

**Issue by Sicryption** [omansak/libvideo#67]
Uri = new System.Collections.Generic.Mscorlib_CollectionDebugView<VideoLibrary.YouTubeVideo>(audio).Items[0].Uri threw an exception of type 'System.InvalidOperationException.

This does not apply on all URLs, however, most music video URLs have this problem. Here are a few along with the source code I am using:

```
var youtube = YouTube.Default;
var video = youtube.GetAllVideos(url);
var audio = video
.Where(e => e.AudioFormat == AudioFormat.Aac && e.AdaptiveKind == AdaptiveKind.Audio)
.ToList();
string workingDir = Directory.GetCurrentDirectory() + "\\";// + "\\Cache\\";
string fileAAC = lastSongName + ".aac"; 
string file = workingDir + fileAAC;
if (audio.Count > 0)
{
byte[] bytes = audio[0].GetBytes();
File.WriteAllBytes(file, bytes);
}
```

Not working Urls:
`https://www.youtube.com/watch?v=8gsGhdZDC-0
https://www.youtube.com/watch?v=yzTuBuRdAyA`

**Comment by win32kbase** [comment]
I'm having this exact issue. Any fixes yet?

**Comment by Sicryption** [comment]
I got around this by using the libvideo that is one of the active pull requests: https://github.com/jamesqo/libvideo/pull/61

**Comment by acosano** [comment]
Hi, Is working 100% for me. Let me know if you need the code, I'm using exact the same code above with MediaToolkit to convert to mp3 as describe in [https://github.com/jamesqo/libvideo/issues/62](url)

**Comment by omansak** [comment]
Fixed. Update 3.0.0
