### ISSUE TITLE
Add a build.cmd script

### ISSUE THREAD

**Issue by jamesqo** [omansak/libvideo#7]
Right now, we require contributors to the repo to have a working copy of Bash. This is great for Linux and OS X users, but it also means that Windows people have to go install some kind of POSIX emulation layer, e.g. Git Bash or Cygwin. It would be nice if we had a `build.cmd` batch script so they could build it natively, but I don't have experience in batch scripting.

**Comment by Krutonium** [comment]
I'll take a look at this in the morning.

**Comment by vipul0092** [comment]
will a powershell script do?

**Comment by Krutonium** [comment]
@vipul0092 The problem with powershell in my experience is that there are a couple of versions of it, and the most commonly installed version is also the least capable. (Also, I am writing a batch script, so ye)
