### ISSUE TITLE
Bug System.InvalidOperationException

### ISSUE THREAD

**Issue by dk0x** [omansak/libvideo#73]
Try this:

VideoLibrary.YouTubeVideo v;
			
v = VideoLibrary.YouTube.Default.GetVideo("https://www.youtube.com/watch?v=HInwDN5UPsY");
uri = v.Uri; // <-- System.InvalidOperationException

in v.uri = https://r8---sn-vh3j-vhne.googlevideo.com/videoplayback?itag=22&ratebypass=yes&ipbits=0&upn=IRIBS2MD2Bk&key=yt6&dur=480.258&initcwndbps=4480000&ei=_4f-WL7RCY29YYL6nnA&lmt=1472004299796290&sparams=dur,ei,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn,expire&expire=1493097567&ms=au&id=o-AP4pOmbCTlSlQszKtTmQLoFGcDkCf489g0xHZ_Q0zIkF&mv=m&mt=1493075486&pl=24&mn=sn-vh3j-vhne&mm=31&source=youtube&requiressl=yes&mime=video/mp4&ip=178.74.109.150&signature=36682F0B5B7967C04CF3C3170221DCD77E7F99693.9A5ECA60D46004B0615D899B5A53838809B5127070

178.74.109.150 - myip ofc, replace it for your ip

this link in browser return HTTP ERROR 403

**Comment by dk0x** [comment]
ok. i try this 

uri = v.GetUriAsync().Result;

anyway System.InvalidOperationException

**Comment by dk0x** [comment]
this Exception throw only if v.IsEncrypted == true

bug with decrypting?

**Comment by frixos25** [comment]
Some solution? 
I want to use the lib if it works fine.

**Comment by handsome-b-wonderful** [comment]
@frixos25 there is an open pull request for a fix. check here: for fork that corrects this and other issues: [](https://github.com/hig-dev/libvideo)

**Comment by dk0x** [comment]
https://github.com/tristanmcpherson/libvideo

in this fork @tristanmcpherson fix this problem

use libvideo by download and put into your solution

**Comment by MJWherry** [comment]
Can the Nuget version be updated with this fix please

**Comment by tristanmcpherson** [comment]
I have a version of libvideo on my MyGet if you would like that
