### ISSUE TITLE
An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.

### ISSUE THREAD

**Issue by Mds92** [omansak/libvideo#76]
When I want to get Videos from `https://www.youtube.com/watch?v=MvK-3Ms3m34&list=RDGMEMJQXQAmqrnmK1SEjY_rKBGA` the following exception occurred in each video Uri property
```
An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
```
How should I get uri?

**Comment by ProbablyBen** [comment]
I solved this issue by removing the https to http.
Assuming you are passed the link as a string, you can do this:
link = link.Replace("https", "http");

**Comment by massimocode** [comment]
I also get the same issue with certain links, for example:
`https://www.youtube.com/watch?v=hS5CfP8n_js`

Using HTTP over HTTPS does not help

**Comment by Lulzphantom** [comment]
Same here, I think it's by copyright

**Comment by Lulzphantom** [comment]
Fix: https://github.com/hig-dev/libvideo , compile project "libvideo-master\src\libvideo.sln" and import "libvideo-master\src\libvideo\bin\Release\libvideo.dll".

**Comment by azizullah-masology** [comment]
I am getting the same issue with some of the videos. @LulzoRean , i compiled "libvideo-master\src\libvideo.sln" from.. https://github.com/hig-dev/libvideo . But i am getting 212 errors on compile.

**Comment by natansystem** [comment]
azizullah-masology tengo el mismo problema al compilar el la solucion. alguien que me pueda ayudar para evitar ese bug del URI address

**Comment by natansystem** [comment]
azizullah-masology I have the same problem when compiling the solution. someone who can help me to avoid that URI bug address

**Comment by natansystem** [comment]
have not yet updated the nugget with this improvement?

**Comment by boswelja** [comment]
I've got the same issue, it only occurs with certain links too (replacing https with http does not help)

**Comment by sandizeher** [comment]
For me issue was solved as proposed by **LulzoRean**. Cloned repo and built it. However, I didn't build entire solution but only libvideo project. Took dll file from bin folder, put it in my own project DLL folder,  referenced it and it works like a charm. 
Thx!

**Comment by i3arnon** [comment]
Hey everybody,
I think I fixed your issues in the latest beta version (https://www.nuget.org/packages/VideoLibrary/1.3.6-beta).
I'm closing this issue but please tell me if you have any issues.

**Comment by dikarux3** [comment]
Guys, just update it to 1.3.7! It's worked for me!
