### ISSUE TITLE
ATTENTION: This project isn't actively maintained. I'm looking for a maintainer.

### ISSUE THREAD

**Issue by jamesqo** [omansak/libvideo#77]
Hi everyone,

As of the time of writing, I haven't committed to this project in over one year. I got notifications about all of the comments/issues that you guys have made, but I just kept putting off responding to you guys because I've lost interest in the project/I was busy. Sorry about that 😢 

I'm looking for someone to become the new maintainer of this project. @i3arnon, I just saw your message on Twitter (which I don't check often anymore), if you're still willing to become the maintainer then I'll gladly let you take over. For other prospective maintainers, send me an email at jamesqko@gmail.com (please include your GitHub username).

**Comment by jamesqo** [comment]
/cc everyone who's made a PR:

@i3arnon @Grimitsu @AdrienTorris @jackw899 @soapergem @gogognome @spoiledtechie @hig-dev

In addition to @i3arnon, I would also particularly be open to @AdrienTorris / @hig-dev becoming maintainer since it looks like they've made PRs that add valuable functionality (#52, #61).

**Comment by i3arnon** [comment]
I guess I'm at a somewhat similar point as you, but I do support (and use) YouCast which depends on libvideo...
So I'll gladly take it over, but mainly for bug fixes and maybe the occasional performance optimization when time allows. I don't plan on revolutionizing it with new features.

If that direction sounds good, let's do it. If someone else has the stamina and the ability to do more, that could be great as well.

**Comment by jamesqo** [comment]
@i3arnon

> So I'll gladly take it over, but mainly for bug fixes and maybe the occasional performance optimization when time allows. I don't plan on revolutionizing it with new features.

That's fine. There seems to be another library for this now, with an even cleaner API: https://github.com/Tyrrrz/YoutubeExplode. Perhaps there is not much point in reinventing the wheel for this project.

Unless someone else responds within 5-7 days, I'll start transferring ownership to you.

**Comment by jamesqo** [comment]
@i3arnon I just sent you an invitation link to become a collaborator. Please accept the invite, then I'll find a way to make you the owner.

**Comment by i3arnon** [comment]
Accepted it.

**Comment by jamesqo** [comment]
@i3arnon You need to delete your fork before I do the transfer, otherwise GitHub tries to create `i3arnon/libvideo` which already exists.

**Comment by i3arnon** [comment]
@jamesqo I've deleted the fork.

**Comment by jamesqo** [comment]
@i3arnon Happy to transfer this project to you. I'm sure you'll do a good job of maintaining it! 😄 

I just pushed a commit that deleted all of my credentials from the README, I think I've removed everything about me but if you find more stuff elsewhere feel free to delete it. The project is in your hands now.

**Comment by i3arnon** [comment]
@jamesqo Thanks, I'll try and live up to the expectations :).
Quick question though: How do I update the nuget?

**Comment by spoiledtechie** [comment]
Yay and welcome @jamesqo!!!!

**Comment by jamesqo** [comment]
@i3arnon I have to add you as an owner on NuGet, too-- I just sent you the invite.

**Comment by jamesqo** [comment]
@i3arnon I see you've accepted the invite. I'll explain here how I published the NuGet packages in the past.

Previously, I used a [custom build script](https://github.com/i3arnon/libvideo/blob/master/build.sh) to automatically create the `nupkg` files, then I would manually go to nuget.org and upload them. The build script is written for MSys, the Linux-like shell that comes with Git Bash.

If you have Git Bash installed, you can first run `./build.sh --msbuild "path/to/MSBuild.exe"` to tell the script the location of MSBuild for subsequent runs. Then, just run `./build.sh --nuget` and it will create the `nupkg` file in a subdirectory of `<repo root>/nuget/`.

If you don't use Git Bash, your best bet is to build the solution manually from VS and run a few commands. Open `libvideo.sln` in VS and build. Then copy the files from `src/<library>/bin/Release/` to `nuget/<library>/lib/portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10/`.

Then you'll need a copy of the nuget executable on your PATH. The first time doing this, run `nuget setApiKey` with your NuGet API key from https://www.nuget.org/account. Next, for each of the `nuspec` files run `nuget pack <nuspec>`, which will create the `nupkg` file for the library.

After you follow the steps above, you should be able to go to nuget.org and upload the `nupkg`s. If you run into any problems, you can drop a comment and ask me.

**Comment by i3arnon** [comment]
@jamesqo Needed to install Microsoft Build Tools 2015 to make it work, but other than that, that's a very nice and simple build script.
You added me to the main nuget, but not to the compat one (I assume unintentionally). Can you add me to that as well and I'll publish?

**Comment by jamesqo** [comment]
@i3arnon Sure thing, I just added you to the compat package.
