### ISSUE TITLE
Some Uri get generated without the signuture

### ISSUE THREAD

**Issue by Qandil** [omansak/libvideo#8]
Hi,

Try getting ?v=RgKAFK5djSk you will notice flv doesnt have that signature.

**Comment by jamesqo** [comment]
@Qandil Sorry, can you please clarify what you're saying? I just tried downloading that video, but I'm getting a 403 error (Forbidden) from HttpClient; I can't tell what you mean by "signature."

**Comment by Qandil** [comment]
@jamesqo if you try with another video that does really work for flv extension you will notice that the uri has a parameter called signature which its seems to authenticate the request, 

For some reason this parameter is not there, maybe something wrong parsing the video links ?

**Comment by jamesqo** [comment]
Looks like [this](https://github.com/jamesqo/libvideo/blob/master/src/libvideo/YouTubeService.cs#L88-L94) seems to be the piece of code in question; the `"signature"` parameter won't get added unless `"s"` or `"sig"` was there before. Maybe this is part of the problem; I'll investigate it further tomorrow. Thanks, Qandil.

**Comment by jamesqo** [comment]
@Qandil Hey! Just pushed a new commit (7dadee8) that should fix this. It seems to be working for me now, can you verify that you're able to download the video with the newer package?

**Comment by Qandil** [comment]
@jamesqo thank you for the update i guess i need to migrate to the new version before i test, right now i keep getting Cannot access a disposed object. Object name: 'System.Net.Http.HttpClient'.

**Comment by Qandil** [comment]
Hi @jamesqo, try using the video i mentioned in the first comment, and try this:

``` csharp
service.GetAllVideos(videoUri)
           .Where(x => x.Format == VideoFormat.Flash && x.AudioBitrate > 0)
           .FirstOrDefault();
```

You will notice that the video.uri throws an exception which yet i don't know why, but maybe it is related.

**Comment by Qandil** [comment]
Closed it by mistake

**Comment by aloisdg** [comment]
@Qandil 

```
service.GetAllVideos(videoUri)
    .Where(x => x.Format == VideoFormat.Flash && x.AudioBitrate > 0)
    .FirstOrDefault();
```

cloud be write

```
service.GetAllVideos(videoUri)
    .FirstOrDefault(x => x.Format == VideoFormat.Flash && x.AudioBitrate > 0);
```

**Comment by jamesqo** [comment]
@aloisdg No, I'm afraid Qandil is right. Opened up a new issue at #16, let's talk about it there.
