### ISSUE TITLE
video size more then 720 not have audio when downloaded

### ISSUE THREAD

**Issue by farazp** [omansak/libvideo#80]
when I try to download video full hd or upper quality not have audio!!!
var videos = await youTube.GetAllVideosAsync(link);
var maxRes = videos.OrderByDescending(v => v.Resolution).FirstOrDefault();

how to download full hd or 4k video with sound and audio?

**Comment by saghen** [comment]
I am encountering this issue as well. A solution would be greatly appreciated.

**Comment by i3arnon** [comment]
YouTube uses Adaptive video for higher resolution videos. That means they use separate streams for video and audio.
You can download them both (see `IsAdaptive` and `AdaptiveKind`) and merge them later with FFmpeg or stay with 720p and lower.
