### ISSUE TITLE
403 (Forbidden)

### ISSUE THREAD

**Issue by szblajos** [omansak/libvideo#82]
Hi guys! Thank you for the great job to create and maintain this awesome project.
Up to now, everything has worked properly with downoading youtube vids...
BUT!
Since February 01. 2018 downloading is not possibe. VideoLibrary.YouTibeVideo.GetBytes() function throws a 403 (Forbidden) exception.
Maybe Youtube made some changes on their site.
Could you please fix this error?

Thank you!

**Comment by omansak** [comment]
++

**Comment by hig-dev** [comment]
It's fixed in my fork: https://github.com/hig-dev/libvideo

**Comment by szblajos** [comment]
Thanks bro! It works like a charm!  :) 👍

**Comment by omansak** [comment]
@hig-dev  Thx :)

**Comment by i3arnon** [comment]
Hey @szblajos, @omansak 
I think I fixed your issues in the latest beta version (https://www.nuget.org/packages/VideoLibrary/1.3.6-beta).
I'm closing this issue but please tell me if you have any issues with any videos.
