### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by darthjames1978** [omansak/libvideo#83]
It appears the majority of YouTube content is broken, the URLs this code returns issue an HTTP 403. 

Perhaps this is for only for video that is monetized?

Rarely a video works with this software.

**Comment by hig-dev** [comment]
It's fixed in my fork: https://github.com/hig-dev/libvideo

**Comment by MusMuss1** [comment]
Doesn't work for videos like [this](https://www.youtube.com/watch?v=Ths_Sokgdds) :(
(https://www.youtube.com/watch?v=Ths_Sokgdds)

**Comment by i3arnon** [comment]
Hey @darthjames1978,
I think I fixed your issues in the latest beta version (https://www.nuget.org/packages/VideoLibrary/1.3.6-beta).
I'm closing this issue but please tell me if you have any issues with any videos.
