### ISSUE TITLE
Broken again ?

### ISSUE THREAD

**Issue by MusMuss1** [omansak/libvideo#84]
1.3.6 Alpha Doesn't work for videos like [this](https://www.youtube.com/watch?v=Ths_Sokgdds) :(
(https://www.youtube.com/watch?v=Ths_Sokgdds)

**Comment by i3arnon** [comment]
Hey @MusMuss1 
Are you sure you've used the alpha version? I have no issue with this specific video.
Do you maybe have other examples?

**Comment by i3arnon** [comment]
Hey @MusMuss1,
I think I fixed your issue and this video works for me with the latest beta version (https://www.nuget.org/packages/VideoLibrary/1.3.6-beta).
I'm closing this issue but please tell me if you have any issues.

**Comment by MusMuss1** [comment]
Hey, everything works so thank you very much :)

2018-04-10 15:13 GMT+02:00 Bar Arnon <notifications@github.com>:
