### ISSUE TITLE
.NET Core 2.0 support

### ISSUE THREAD

**Issue by dajuric** [omansak/libvideo#86]
Are there any plans to support .NET Core 2.0 ?
(to release the compatible packages)

**Comment by i3arnon** [comment]
Yes :)
I've just published a beta package supporting .NET standard: https://www.nuget.org/packages/VideoLibrary/2.0.0-beta

Could you maybe try it out and share whether it works for you?
Here's the PR I'm using to track this move: https://github.com/i3arnon/libvideo/pull/92

**Comment by dajuric** [comment]
Thanks :)
