### ISSUE TITLE
Error on GetBytes

### ISSUE THREAD

**Issue by HiImLesic** [omansak/libvideo#87]
I just installed the nuget and I basically get an InvalidOperationException on any link I try to download on GetBytes.

`var youtube = YouTube.Default;
				var videos = youtube.GetAllVideos(this.videoToDownload.Link);
				var audio = videos
					.Where(v => v.AudioFormat == AudioFormat.Aac && v.AdaptiveKind == AdaptiveKind.Audio)
					.ToList();
				if (audio.Count > 0)
				{
					byte[] bytes = audio[0].GetBytes();
					File.WriteAllBytes(file + ".aac", bytes);
				}`

Example link I get an error on:
https://www.youtube.com/watch?v=94bGzWyHbu0

**Comment by i3arnon** [comment]
@HiImLesic 
Did you install the latest stable version of the nuget (version 1.3.5)?
Could you try using the latest beta version instead (1.3.6-beta) and tell me if you still get these errors?

**Comment by HiImLesic** [comment]
Yes, I am using the latest stable 1.3.5.
Where can I get the latest beta version? It's not on nuget, is it?

**Comment by i3arnon** [comment]
It is (https://www.nuget.org/packages/VideoLibrary/1.3.6-beta)
If you add the nuget via Visual Studio you need to check the little box that says "include prerelease" (see https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages#installing-and-updating-pre-release-packages)

**Comment by HiImLesic** [comment]
Good stuff, this is working, thank you!

**Comment by i3arnon** [comment]
Great to hear.
I'll soon release a stable build, I just wanted to make sure this works for other people as well...
