### ISSUE TITLE
Save large video error

### ISSUE THREAD

**Issue by romanrakus** [omansak/libvideo#88]
Hi,

When I try to save large video(couple hours) I have following exception:
`System.Net.Http.HttpRequestException: 'Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.'`

I think it should be fixed in the library or somehow configurable.

**Comment by oSumAtrIX** [comment]
Since we reach the max value of what an integer can represent, we need to split the buffer

**Comment by romanrakus** [comment]
@oSumAtrIX I believe that's should be a configurable option.

**Comment by oSumAtrIX** [comment]
@romanrakus didn't find it in the docs
