### ISSUE TITLE
FormatCode for 4k resolution FOUND!

### ISSUE THREAD

**Issue by serban-mihai** [omansak/libvideo#89]
Nice work with the lib in first place.
By scrapping the HTML plain text I got that YouTube introduced a new code for 2160p resolutions which is **313**, please update the Resolution FormatCode in src/libvideo/YouTubeVideo.Format.cs
 with a 
`case: 313 `
when returning 2160 and update the NuGet Package. This should allow us to download videos at 4k resolution.
![screenshot 9](https://user-images.githubusercontent.com/34487580/39670531-8daf8444-510f-11e8-8d68-97d8f91127ad.png)
![screenshot 8](https://user-images.githubusercontent.com/34487580/39670532-8dd41ea8-510f-11e8-8dac-ee5d8549c3e2.png)

**Comment by i3arnon** [comment]
Fixed: https://www.nuget.org/packages/VideoLibrary/1.3.7
Thanks for pointing this out.
Please tell me if the update doesn't work for you for some reason.
