### ISSUE TITLE
Xamarin Forms

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [omansak/libvideo#93]
I want to use xamarin forms, how do I?

**Comment by amirvenus** [comment]
I am trying to use it on Xamarin.Forms.UWP but I get an exception.

**Comment by i3arnon** [comment]
@amirvenus which exception?

**Comment by andersonvieiragomeslopes** [comment]
@amirvenus do you have any tutorial to use with xamarin forms android?

**Comment by narqs** [comment]
You can use libvideo in Xamarin android as you would do in wpf.

**Comment by andersonvieiragomeslopes** [comment]
@narqs Yes, since no renderer is needed, it is that it has nothing specifying if it is necessary, when it involves videos the forms xamarin is very complicated.

**Comment by andersonvieiragomeslopes** [comment]
I will try to implement based on xamarin forms UWP, in case of problems, reopen this problem, thanks guys.
