### ISSUE TITLE
No Sound?

### ISSUE THREAD

**Issue by npsiegfried** [omansak/libvideo#94]
Whenever I download a video in any resolution and format I get no sound with the video. When I check the audio properties of the video there's nothing listed. Is there a fix for this?

**Comment by i3arnon** [comment]
YouTube uses adaptive video for resolutions above 720p. That means the video and audio streams are separate.
You can download both and merge them later with ffmpeg, or filter the videos using `AdaptiveKind` (keep in mind that limits you to 720p).
