### ISSUE TITLE
HTTP ERROR 403 Forbidden

### ISSUE THREAD

**Issue by omansak** [omansak/libvideo#97]
it does not download a lot videos.
examples : https://www.youtube.com/watch?v=DcgPCU10Bek&list=RDNJkBtgxlzjQ

**Comment by omansak** [comment]
New signature javascript

```
var TK = {
  xa: function(a, b) {
    var c = a[0]
    a[0] = a[b % a.length];
    a[b % a.length] = c;
  },
  do: function(a) {
    a.reverse();
  },
  BH: function(a, b) {
    a.splice(0, b);
  }
};
{
  UK = function(a) {
    a = a.split("");
    TK.BH(a, 2);
    TK.xa(a, 13);
    TK.BH(a, 1);
    TK["do"](a, 37);
    TK.BH(a, 1);
    TK.xa(a, 69);
    TK["do"](a, 36);
    return a.join("");
  };
}

```

**Comment by omansak** [comment]
#98

**Comment by Gr3gorywolf** [comment]
@omansak it still not working actually even using your fix im pretty worry about :,(   @omansak pls help us

**Comment by omansak** [comment]
@Gr3gorywolf can you send video that has error ?

**Comment by Gr3gorywolf** [comment]
almost all encrypted videos have this error

**Comment by Gr3gorywolf** [comment]
for example---->https://www.youtube.com/watch?v=zuQGx1H1Qh8

**Comment by Gr3gorywolf** [comment]
can you please send a pre-compiled dll with this bug fixed pls

**Comment by omansak** [comment]
#98 updated.

**Comment by Gr3gorywolf** [comment]
👍

**Comment by ConfusedRunningGuy** [comment]
sorry for what is probably a silly question.  How do I implement the new javascript signature on compiled component?
